// src/lab/sdf-zombie/webgpu/explosion-vfx.ts
//
// PROCEDURAL GPU explosion burst — the visual half of `resolveExplosion`'s
// `BurstVisual` (../explosion-aoe.ts). No image assets, no atlas, no flipbook:
// every pixel of fire, smoke, ember and shockwave is generated by TSL node
// graphs evaluated on the GPU, advected by a `time` uniform and remapped
// through a blackbody-ish ramp.
//
// ── BILLBOARD BUDGET (the number a caller needs) ────────────────────────
//   fire  14   additive, staggered bloom-then-stretch billboards
//   smoke  8   normal-blended, late-blooming rising billboards
//   ember 12   additive ballistic streaks, CPU-stepped, pooled
//   ring   1   additive expanding shockwave annulus
//   ─────────
//   35 per burst at the default tuning (the brief's "well under ~40").
// Hard caps are 20 + 12 + 18 + 1 = 51 per burst and at most
// EXPLOSION_VFX_LIMITS.maxBursts (6) bursts are ever live, so the module can
// never draw more than 306 billboards.
//
// DRAW CALLS: 4 total, not 4-per-burst. Each layer is ONE dynamic
// BufferGeometry the CPU refills each frame (vertices baked in WORLD space,
// geometry at the origin, frustumCulled off) and ONE node material — 1 fire
// + 1 smoke + 1 ember + 1 ring. A fifth live burst costs zero extra draw
// calls. The CPU half is deliberate: camera basis, roll and envelope stay in
// testable pure code, while every *look* decision — noise, ramp, falloff —
// stays in the node graph.
//
// ── THE TRANSPARENCY TRAP, AND WHAT THIS FILE DOES ABOUT IT ─────────────
// kit-overlay.ts:78-90 writes up the failure: the SDF layer composites its
// flesh as a fullscreen quad that DEPTH-TESTS against the polygon depth
// buffer, so translucent geometry drawn in the polygon pass is either erased
// by the flesh (depthWrite off) or punches a hole showing the background
// (depthWrite on). character-effects.ts:6-8 records the repo's fix, and this
// module is designed to be another tenant of it: the caller adds `vfx.object`
// to the SEPARATE effects scene that game-main renders AFTER the composite
// with `renderer.autoClear = false`. In that position `transparent: true`
// composes correctly against the finished frame, and `depthTest: true` still
// lets walls and bodies occlude a burst.
//
// Concretely, for the two WebGPU-specific landmines this repo has hit:
//   * `alphaHash` is NOT used anywhere in this file. blood-view-gpu.ts:154
//     records that hashed coverage rendered the quads as unshaped translucent
//     SQUARES on the WebGPU backend (the map's alpha never gated coverage).
//     createExplosionLookMaterial keeps the path reachable behind
//     `alphaControl: 'hash'` purely so the spike page can re-photograph the
//     failure next to the working one.
//   * `alphaTest` is NOT used either. blood-view-gpu notes a cutout is what
//     makes its droplet path survive the composite, but a cutout has no soft
//     glow, and a fireball is entirely glow. Coverage comes from the node
//     graph's alpha instead — `colorNode.w`, which NodeMaterial assigns
//     straight to `diffuseColor.a` (NodeMaterial.js:856-862) — plus the blend
//     factors, which were read out of this build rather than assumed:
//       AdditiveBlending, premultipliedAlpha:false -> (SrcAlpha, One)
//       NormalBlending,   premultipliedAlpha:false -> (SrcAlpha, OneMinusSrcAlpha)
//     (WebGPUPipelineUtils.js:560-575.) So `colorNode = vec4(rgb, coverage)`
//     adds rgb*coverage for fire and lerps rgb by coverage for smoke — the
//     standard non-premultiplied behaviour on this backend.
//
// ── DETERMINISM ─────────────────────────────────────────────────────────
// No Math.random() anywhere, per-frame or at spawn. All per-billboard
// randomness is drawn ONCE at spawn() from a seeded mulberry32 (imported from
// game-weapon.ts, the repo's canonical copy) and stored in preallocated
// Float32Arrays; update() only reads it. spawn(visual, seed) pins the seed for
// a capture; a driver that pins the seed sequence AND the dt sequence gets a
// reproducible frame.
//
// EVERYTHING IS PREALLOCATED at construction: geometries, attributes,
// materials, uniforms and all per-slot parameter storage. spawn() and
// update() allocate nothing.
//
// ROUTING NOTE: vertices are world-space, so `object` must be added to a
// scene whose root transform is the identity (characterEffects.scene is).

import * as THREE from 'three/webgpu';
import { MeshBasicNodeMaterial } from 'three/webgpu';
import {
  attribute, clamp, float, length, linearDepth, min, mix, mx_fractal_noise_float,
  positionWorld, smoothstep, uniform, vec2, vec3, vec4,
} from 'three/tsl';
import { mulberry32 } from './game-weapon';
import { curlVector } from './curl-volume-node';
import { softParticleFade } from './soft-fade';
import type { Vec3 } from '../types';
import type { BurstVisual } from '../explosion-aoe';

// ————————————————————————————————————————————————————————————————————————
// Public types (the interface other code is written against)
// ————————————————————————————————————————————————————————————————————————

export interface ExplosionVfxTuning {
  /** Overall additive fire brightness multiplier. */ gain: number;
  /** Fireball half-height in metres for a 1.0-scale burst, times BurstVisual.heightM. */
  fireScale: number;
  /** Seconds the whole burst lasts. */ lifeSec: number;
  /** Number of fire billboards per burst. */ fireCount: number;
  /** Number of smoke billboards per burst. */ smokeCount: number;
  /** Number of ballistic embers per burst. */ emberCount: number;
  /** Shockwave ring speed (m/s) and its fade. */ ringSpeedMps: number;
  /** Peak dynamic-light intensity fed back to the caller (0 disables). */
  lightIntensity: number;
  /** Base seed for the per-burst LCG when spawn() gets no pinned seed. */
  seed: number;
  /** SMOKE opacity multiplier. 0 kills the normal-blended layer entirely
   *  (the smoke A/B); 1 is the authored density. */
  smokeOpacity: number;
  /** SHOCKWAVE ring alpha multiplier. 0 disables the ring. */
  ringOpacity: number;
  /**
   * THE PLUME'S TWO HEIGHTS, in half-heights above the burst's centre: where
   * the fire NECK tops out and where the smoke CAP does. These are what make a
   * mushroom instead of a ball — the neck's clamp is what stops the fire
   * growing into a sphere, and the gap between the two is the stem.
   *
   * They are the HEIGHT at the end of the layer's life, not a clamp on a
   * curve, so the silhouette is stated here rather than deduced from one.
   */
  plumeNeckH: number;
  plumeCapH: number;
  /**
   * How flat the smoke cap draws at the end of its life, as a fraction of the
   * cap's own horizontal size. 1 is a sphere; the owner's reference is a
   * mushroom, so the cap ends up WIDER THAN TALL — the one place this effect
   * is allowed to un-stretch, and the reason `stretchY` alone could never
   * produce the shape (it is >= 1 everywhere, i.e. everything is taller than
   * it is wide).
   */
  capFlatten: number;
  /**
   * EMBER speed in half-heights per second. Was absolute m/s (3.5-14.5, i.e.
   * sparks crossing ~4 m — about 11 half-heights — while the plume they came
   * out of is 2). Sparks that outrun their own explosion by 10x read as a
   * separate effect, so this now scales with the burst like everything else.
   */
  emberSpeedPerH: number;
  /**
   * How far the ground shockwave front may travel, in half-heights. The ring's
   * speed is a real m/s (9 by default) and its life is short, but nothing tied
   * its REACH to the burst: at the shipped size the front ran 4.2 m out of a
   * 0.84 m plume — twelve times the fireball it came from, a swept ring on the
   * far side of the room. Clamped so the front reads as the plume's own
   * pressure wave, still decelerating, still fading.
   */
  ringReachH: number;
  /**
   * THE PLUME A/B, 0..1. 1 is the mushroom; 0 is the round fireball this
   * effect used to be. It blends the three terms that ARE the shape — the
   * neck's convergence, the cap's outward roll, and the cap's flattening —
   * back to the constant 1.0 they were, and it blends the smoke's spawn
   * azimuth from the rim back to a uniform-in-the-ball draw.
   *
   * It exists because "is it a mushroom yet" is the owner's call and the only
   * honest way to make it is a switch between the two, in one boot, on the
   * same burst. The spawn DISTRIBUTION is deliberately included: shape here is
   * not only the envelopes — a uniform draw in the unit ball puts most
   * billboards near the centre whatever the envelopes do.
   */
  plumeMix: number;
  /**
   * Share of the FIRE billboards that take the CAP envelope instead of the
   * neck's, 0..1. 0 is fire-as-column-only (the bottom-heavy read the atlas
   * measurement rejects); 1 is every fire billboard riding the cap, which
   * leaves no column at all.
   */
  fireCapShare: number;
  /**
   * The CAP fire's flatness at the end of its life, 0..1 — the neck never
   * flattens; this is what stops the top of the plume being a sphere.
   */
  capFireFlatten: number;
  /**
   * CURL MOTION (explosion-curl task). How hard the SHARED divergence-free
   * curl volume (curl-volume-node.ts) domain-warps the fire and smoke noise
   * lookup, in noise-domain units. 0 is the game's default and contributes
   * EXACTLY zero — the pre-curl scrolling look, unchanged — so the new swirl
   * is opt-in; the spike page turns it on and the owner decides whether to
   * lift the game default. Bounds [0, 2]. The applied amplitude is budgeted by
   * `curlWarpGain` so that a tight `curlScale` cannot compress the lookup (the
   * straight-cross defect); at the shipped `curlScale` (18 m) the full value is
   * applied.
   */
  curlStrength: number;
  /**
   * World metres per curl-volume repeat: the shader samples the field at
   * `fragmentWorld / curlScale`. Smaller is more, tighter swirl cells (a
   * fireball is a few metres across, so ~2.5 reads as a rolling ball where the
   * flame cards' ~6 m body scale would be one cell). Only meaningful when
   * `curlStrength > 0`.
   *
   * IT ALSO SETS THE COMPRESSION BUDGET: the warp's spatial gradient grows as
   * `curlStrength / curlScale`, and once it compresses the noise lookup a
   * single fire billboard shows a straight cross. The measured clean bound is
   * `strength / curlScale <= CURL_WARP_SAFE_RATIO` (0.06), so the shipped 1.1
   * needs **18 m** — at 6 m the full strength still crossed (see the 2026-09-18
   * NOTES, second pass). Below that scale the applied amplitude is scaled down
   * with `curlScale` (`curlWarpGain`). Ship at 18.
   */
  curlScale: number;
  /**
   * SOFT-PARTICLE FADE distance in metres (soft-fade.ts): translucent fire and
   * smoke fade out as they approach the scene surface behind them, so the hard
   * straight cut where a quad meets the floor or a wall becomes a gradient.
   * 0 is the game's default and is fully inert (the identical frame). Bounds
   * [0, 2] metres.
   */
  softFade: number;
}

export const EXPLOSION_VFX_TUNING: ExplosionVfxTuning = {
  gain: 1.35,
  fireScale: 1.0,
  lifeSec: 1.5,
  fireCount: 14,
  smokeCount: 8,
  emberCount: 12,
  ringSpeedMps: 9,
  lightIntensity: 5,
  seed: 0x5eed1234,
  smokeOpacity: 1,
  ringOpacity: 1,
  // 2.0 and 2.6 half-heights: at the shipped size (halfH 0.84 m) that is a
  // 1.7 m neck under a cap topping out at 2.2 m, against the atlas reference's
  // 1.65 m quad. The numbers are in HALF-HEIGHTS, so ?fxsize zooms the whole
  // silhouette without changing its proportions.
  plumeNeckH: 1.35,
  plumeCapH: 2.0,
  capFlatten: 0.55,
  emberSpeedPerH: 4.5,
  // 1.4, not 2.4: measured on the differential capture, a 2.4-half-height
  // ground ring put 75k of the burst's 93k changed pixels in a flat band across
  // the bottom of the frame — the ring WAS the explosion as far as the frame
  // was concerned, and it is what made the burst read wide and low whatever the
  // plume above it did. The reference's ground burst has a small base.
  ringReachH: 1.4,
  plumeMix: 1,
  fireCapShare: 0.5,
  capFireFlatten: 0.5,
  // BOTH NEW SWITCHES SHIP OFF: the game's explosions are the pre-curl look
  // until the owner flips these (one line each). See the interface above.
  // curlScale already carries the ship value (18, the compression-safe scale
  // for curlStrength 1.1) so a one-line strength flip cannot reintroduce the
  // cross; at curlStrength 0 it multiplies nothing.
  curlStrength: 0,
  curlScale: 18,
  softFade: 0,
};

export interface ExplosionVfx {
  /** Add THIS to the effects overlay scene (see routing in the file header). */
  readonly object: THREE.Object3D;
  /**
   * Spawn one burst at visual.at. Safe to call several times per second.
   *
   * `seed` is OPTIONAL and purely additive to the required signature: the
   * ordinary call is `spawn(visual)`, which draws its seed from the tuning
   * base plus a spawn counter. A capture driver that wants a reproducible
   * burst passes a pinned seed, which makes that burst independent of how many
   * bursts came before it.
   */
  spawn(visual: BurstVisual, seed?: number): void;
  /** Advance simulation/animation. `camera` is used for billboard facing. */
  update(dtSec: number, camera: THREE.Camera): void;
  /** The current peak light intensity this frame, for the caller to feed the
   *  dynamic light list. 0 when no burst is alive. */
  readonly lightIntensity: number;
  /** Live tuning seam (a test page / panel drives this). */
  setTuning(t: Partial<ExplosionVfxTuning>): void;
  readonly tuning: ExplosionVfxTuning;
  /** Desktop-only quick switch between fire looks, for the owner's A/B. */
  readonly activeBursts: number;
  /**
   * THE BURST'S OWN SHAPE, IN METRES — what the effect actually emitted this
   * frame, per layer: how many quads, the world-space box they cover, and how
   * their mass is distributed vertically (the mean height and the quartile
   * split).
   *
   * WHY AT THE SOURCE. The only other way to ask "is it a mushroom" is to
   * photograph the burst and read the changed pixels, and that instrument is
   * confounded twice over: the ground RING is a large low-lying annulus that
   * dominates the changed area (so a whole-burst mass centroid is mostly the
   * ring's height), and the changed region's BOUNDING BOX is re-cut by a single
   * stray pixel (so any band split by height reorders between boots). This is
   * deterministic, per layer, in world units, and it needs no GPU readback.
   */
  readonly layerExtents: Record<'fire' | 'smoke' | 'ember' | 'ring', LayerExtent>;
  /** The half-height this frame's bursts were laid out against, in metres —
   *  the number every extent above should be read RELATIVE to. */
  readonly burstHalfHeightM: number;
  dispose(): void;
}

/** One layer's emitted shape this frame, in world metres. */
export interface LayerExtent {
  /** Quads written (0 when the layer drew nothing). */
  count: number;
  /** World box of the quad CENTRES — not their billboard corners: a quad's own
   *  size is the billboard, and mixing the two makes a wide quad's box look
   *  like a wide cloud. */
  min: [number, number, number];
  max: [number, number, number];
  /** Mean centre height, and the mean height of the bottom and top quartiles —
   *  the shape question ("is the mass up top") as three numbers. */
  meanY: number;
  lowQuartileY: number;
  highQuartileY: number;
}

// ————————————————————————————————————————————————————————————————————————
// Pool shape — the whole effect's memory is sized from these at construction
// ————————————————————————————————————————————————————————————————————————

export const EXPLOSION_VFX_LIMITS = {
  /** Live bursts. A seventh detonation recycles the oldest slot. */
  maxBursts: 6,
  maxFirePerBurst: 20,
  maxSmokePerBurst: 12,
  maxEmberPerBurst: 18,
  /** Billboards one default burst draws: 14 fire + 8 smoke + 12 embers + 1 ring. */
  billboardsPerDefaultBurst: 35,
} as const;

/** Segments around the shockwave annulus (one quad each). */
const RING_SEGMENTS = 48;
/** Annulus half-thickness as a fraction of its radius. */
const RING_THICKNESS_FRAC = 0.16;
/** Ring lifetime as a fraction of tuning.lifeSec — the front is FAST. */
const RING_LIFE_FRAC = 0.4;
/** Ring start radius as a fraction of the burst half-height. */
const RING_START_FRAC = 0.22;
/** Ember lifetime as a fraction of tuning.lifeSec. */
const EMBER_LIFE_FRAC = 0.9;
/** Sparks fall harder than g: they are light, small, and read as thrown heat. */
const EMBER_GRAVITY_MPS2 = -11;
/** Linear drag on sparks, 1/s — they die of air, not of gravity. */
const EMBER_DRAG = 2.0;
/** Longest dt one update() will integrate: a 200 ms hitch must not teleport
 *  the shockwave front across the room. */
const MAX_UPDATE_STEP_SEC = 0.05;
/** Ground-burst fireball centre above the floor, × half-height. */
const GROUND_CENTRE_FRAC = 0.5;
/** Fire/smoke billboard base half-size, × half-height (before the envelope). */
const FIRE_BASE_SIZE = 0.62;
const SMOKE_BASE_SIZE = 0.95;

const VERTS_PER_QUAD = 4;
const INDICES_PER_QUAD = 6;
const TAU = Math.PI * 2;

// ————————————————————————————————————————————————————————————————————————
// Pure helpers — no THREE, no GPU. These are what the unit tests drive.
// ————————————————————————————————————————————————————————————————————————

export function clamp01(x: number): number {
  return x < 0 ? 0 : x > 1 ? 1 : x;
}

/** GLSL-style smoothstep on scalars, so the envelopes below are plain
 *  arithmetic the tests can reason about. */
export function smoothstep01(e0: number, e1: number, x: number): number {
  if (e1 === e0) return x < e0 ? 0 : 1;
  const t = clamp01((x - e0) / (e1 - e0));
  return t * t * (3 - 2 * t);
}

/** Where a burst's fireball sits, and how its shockwave ring is oriented. */
export interface BurstAnchor {
  /** Detonation point, verbatim. */
  at: Vec3;
  /** Y of the plume's bottom. Air: `at.y − halfHeightM`. Ground: `at.y`. */
  baseY: number;
  /** Y of the fireball's centre. Air: `at.y`. Ground: `baseY + halfHeightM/2`. */
  centreY: number;
  /** Fireball half-height (m) — `fireScale × heightM`. */
  halfHeightM: number;
  /** `flat` = the ring lies on the floor at `at.y` (a ground-burst dome);
   *  `billboard` = the ring faces the camera at the burst centre (an airburst
   *  shell, whose silhouette is a circle). */
  ring: 'flat' | 'billboard';
  /** `plume` billboards lock their up axis to world +Y, so a column of smoke
   *  climbs the screen instead of leaning with the camera; `ball` billboards
   *  take the camera's full basis, which is what makes a fireball a ball. */
  orient: 'plume' | 'ball';
}

/**
 * Air vs ground anchoring, as plain numbers.
 *
 * AIR    — the blast has room, so the fireball is CENTRED on the detonation
 *          point and grows in every direction.
 * GROUND — the floor is in the way, so the fireball's BOTTOM is pinned at
 *          `at.y` and the plume blooms upward out of the crater; the ring lies
 *          flat on the floor. That is the brief's rule: `kind === 'ground'`
 *          → the ring/dome sits at `at.y` and the plume rises.
 */
export function burstAnchor(
  kind: 'air' | 'ground',
  at: Vec3,
  halfHeightM: number,
): BurstAnchor {
  const ground = kind === 'ground';
  return {
    at: [at[0], at[1], at[2]],
    baseY: ground ? at[1] : at[1] - halfHeightM,
    centreY: ground ? at[1] + halfHeightM * GROUND_CENTRE_FRAC : at[1],
    halfHeightM,
    ring: ground ? 'flat' : 'billboard',
    orient: ground ? 'plume' : 'ball',
  };
}

/** One fire billboard's state at local age `u` (0..1). */
export interface FireSample {
  /** 0..1 brightness — fast ignition, slower burn-out. */
  intensity: number;
  /** Radius multiplier applied to the billboard's base half-size. */
  radius: number;
  /** Upward travel, in units of the burst half-height. */
  rise: number;
  /** Vertical stretch — the "bloom then stretch upward" half of the brief. */
  stretchY: number;
  /**
   * Vertical squash of the billboard, 0..1. 1 for the NECK (a column, taller
   * than wide); the CAP role is the one that flattens, which is what makes the
   * silhouette a mushroom rather than a ball with a tail.
   */
  flatten: number;
  /**
   * HORIZONTAL SPREAD multiplier, 0..1 — the term that used to be the same
   * number as the vertical one and made a ball.
   *
   * The fire is the plume's NECK: it flares outward at ignition (the blast's
   * own ground burst) and then CONVERGES, so the column rising out of the
   * crater is narrower than the crater rather than a self-similar sphere
   * growing in every direction at once.
   */
  flare: number;
}

/**
 * The fire envelope. `u` is the billboard's own LOCAL age: the per-billboard
 * stagger (`delay`/`span`, drawn at spawn) is applied by the caller, which is
 * what stops fourteen billboards pulsing as one.
 *
 * Shape: a hard ignition over the first ~12% (a burst reads as a FLASH, not a
 * fade-in), then a burn-out complete by u = 1. The radius only ever grows,
 * and the stretch and the rise both ramp in later — so the same billboard
 * starts as a hot ball and ends as a lick of flame.
 *
 * THE RISE ENDS AT `plumeNeckH`. `radius` still grows, but this layer is a
 * COLUMN under the cap: if it kept climbing past the cap's own height the
 * silhouette would be a sphere again, which is the shape this replaced.
 */
export function fireEnvelope(u: number, plumeNeckH = 1.35): FireSample {
  const t = clamp01(u);
  return {
    intensity: smoothstep01(0, 0.06, t) * (1 - smoothstep01(0.3, 1, t)),
    radius: 0.35 + 0.62 * Math.sqrt(t),
    // The knob IS the height the neck tops out at (t = 1), so the silhouette
    // is stated in the tuning rather than deduced from a curve and a clamp.
    rise: plumeNeckH * Math.pow(t, 1.5),
    stretchY: 1 + 0.95 * t,
    // A column, not a cap: this role never flattens.
    flatten: 1,
    // 1.15 at ignition (the crater flare) collapsing to 0.3: the neck.
    flare: 1.15 - 0.85 * smoothstep01(0.05, 0.55, t),
  };
}

/**
 * The fire that rides the CAP — the hot top of a mushroom.
 *
 * WHY FIRE NEEDS A ROLE AT ALL. Measured against the `?explosionfx=atlas`
 * reference, a burst whose fire is ALL neck and whose smoke is all cap comes
 * out bottom-heavy: the fire converges into a bright column at the crater while
 * the only thing up top is smoke at `?fxsmoke`'s opacity, which is a DIM layer
 * on purpose (the owner cut it so the gibs stay visible). The reference's mass
 * sits high — its top quarter of changed pixels outweighs its bottom quarter by
 * an order of magnitude — and no amount of envelope tuning reaches that without
 * a bright layer up there. So a share of the fire billboards take this
 * envelope instead: they climb to the cap, roll outward, and flatten.
 */
export function capFireEnvelope(u: number, capTopH = 2.0, capFlatten = 0.55): FireSample {
  const t = clamp01(u);
  return {
    // Slower to light than the neck — the cap forms after the column — and it
    // HOLDS: a cloud that has stopped burning reads as the top of the plume.
    intensity: smoothstep01(0.05, 0.35, t) * (1 - smoothstep01(0.55, 1, t)),
    radius: 0.5 + 0.85 * Math.sqrt(t),
    rise: capTopH * Math.pow(t, 0.65),
    // Stretched on the way up, then flattened as it rolls out.
    stretchY: 1 + 0.5 * t,
    flatten: 1 - (1 - capFlatten) * smoothstep01(0.35, 0.9, t),
    // The cap rolls OUTWARD rather than converging: this is the term that
    // separates the two roles.
    flare: 0.45 + 0.85 * smoothstep01(0.1, 0.6, t),
  };
}

/** One smoke billboard's state at local age `u` (0..1). */
export interface SmokeSample {
  /** 0..1 opacity — the density the material multiplies into coverage. */
  density: number;
  radius: number;
  rise: number;
  /** 0..1 self-illumination from the fireball the smoke was born in. */
  glow: number;
  /** Horizontal spread multiplier, 0..1 — the cap's outward roll. */
  flare: number;
  /** Vertical squash of the billboard, 0..1 — 1 is round, `capFlatten` is the
   *  end of life. THIS is the term the shape lives in: everything else in both
   *  envelopes is `stretchY >= 1`, i.e. taller than wide, which cannot be a
   *  mushroom however it is tuned. */
  flatten: number;
}

/**
 * The smoke envelope. Slower and further-travelling than fire by design: the
 * caller staggers smoke to spawn LATE (delay 0.2–0.55 of the burst), so the
 * column is still climbing when the fire is already out. `glow` decays four
 * times faster than the density — smoke is briefly lit from inside and is then
 * just dark.
 *
 * The smoke is the CAP, so its radius PLATEAUS rather than growing without
 * bound: `t^0.5` reaches 87% of its total in the first quarter and then barely
 * moves, which is a cloud that has finished rolling outward. Its rise ENDS at
 * `plumeCapH`, which must be above `plumeNeckH` — the gap between the two is
 * the stem, and it is the whole silhouette.
 */
export function smokeEnvelope(u: number, plumeCapH = 2.0, capFlatten = 0.55): SmokeSample {
  const t = clamp01(u);
  return {
    density: smoothstep01(0.02, 0.3, t) * (1 - smoothstep01(0.45, 1, t)),
    radius: 0.5 + 1.15 * Math.sqrt(t),
    // Same rule as the neck: the knob is the height at the end of life. The
    // EXPONENT is what differs — 0.7 climbs early and then crawls, which is a
    // cloud that has nearly finished rising while the fire under it is still
    // burning.
    rise: plumeCapH * Math.pow(t, 0.7),
    glow: 1 - smoothstep01(0, 0.45, t),
    // The cap rolls OUTWARD over its first half and then holds: 0.3 -> 1.
    flare: 0.3 + 0.7 * smoothstep01(0.1, 0.5, t),
    // Flattening follows the flare, so the widening and the squashing are one
    // read rather than two.
    flatten: 1 - (1 - capFlatten) * smoothstep01(0.3, 0.9, t),
  };
}

/** One shockwave ring's state at local age `u` (0..1). */
export interface RingSample {
  radiusM: number;
  alpha: number;
}

/**
 * The shockwave front. The front DECELERATES (`ease` is a fast-out curve, so
 * most of the radius is gained in the first third) and the fade is steeper
 * than the growth: a blast front that lingers reads as a smoke ring, which is
 * the wrong effect.
 */
export function ringEnvelope(
  u: number, startRadiusM: number, speedMps: number, lifeSec: number,
): RingSample {
  const t = clamp01(u);
  const ease = 1 - Math.pow(1 - t, 2.2);
  return {
    radiusM: startRadiusM + speedMps * lifeSec * ease,
    alpha: Math.pow(1 - t, 1.6),
  };
}

/** The dynamic-light envelope: a near-instant spike, then a fall. */
export function lightEnvelope(u: number): number {
  const t = clamp01(u);
  return smoothstep01(0, 0.05, t) * Math.pow(1 - t, 2.2);
}

/** A ballistic ember, mutated in place by {@link stepEmber}. */
export interface EmberState {
  px: number; py: number; pz: number;
  vx: number; vy: number; vz: number;
}

/**
 * Semi-implicit Euler with linear drag — the ember half of "ballistic".
 * Velocity is damped, then gravity applied, then position integrated with the
 * NEW velocity, so a step never adds energy. No allocation: the caller owns a
 * fixed pool.
 */
export function stepEmber(
  e: EmberState, dtSec: number, gravityMps2: number, drag: number,
): void {
  const damp = Math.max(0, 1 - drag * dtSec);
  e.vx *= damp;
  e.vz *= damp;
  e.vy = e.vy * damp + gravityMps2 * dtSec;
  e.px += e.vx * dtSec;
  e.py += e.vy * dtSec;
  e.pz += e.vz * dtSec;
}

/**
 * Slot-ring allocator: the first retired slot, or the OLDEST live one when
 * every slot is busy (a rapid-fire stream must recycle, never refuse). An age
 * of `Infinity` means "never used" and is always taken first. The free test is
 * a plain `>=` so a NaN age counts as LIVE, never as free — a corrupt age must
 * not silently steal a slot another burst is still using.
 */
export function findFreeSlot(ages: ArrayLike<number>, lifeSec: number): number {
  let oldest = 0;
  let oldestAge = -Infinity;
  for (let i = 0; i < ages.length; i++) {
    const age = ages[i]!;
    if (age >= lifeSec) return i;
    if (age > oldestAge) { oldestAge = age; oldest = i; }
  }
  return oldest;
}

/** The seed one burst's per-billboard randomness is drawn from. A caller that
 *  pins `seed` gets a reproducible burst regardless of how many bursts came
 *  before it — that is the hook a capture driver uses. */
export function burstSeed(pinned: number | undefined, sequence: number, base: number): number {
  return (pinned === undefined ? base + sequence : Math.floor(pinned)) >>> 0;
}

function clampNum(x: number, lo: number, hi: number): number {
  if (!Number.isFinite(x)) return lo;
  return x < lo ? lo : x > hi ? hi : x;
}

function clampCount(x: number, cap: number): number {
  if (!Number.isFinite(x)) return 0;
  const n = Math.floor(x);
  return n < 0 ? 0 : n > cap ? cap : n;
}

/** Clamp an arbitrary tuning patch into the pool's real limits. Fractional
 *  counts (WebGPU cannot draw 3.5 billboards) and a life of 0 are the two ways
 *  a panel can hand this module something it cannot honour. */
export function clampTuning(t: ExplosionVfxTuning): ExplosionVfxTuning {
  const L = EXPLOSION_VFX_LIMITS;
  return {
    gain: clampNum(t.gain, 0, 64),
    fireScale: clampNum(t.fireScale, 0.05, 8),
    lifeSec: clampNum(t.lifeSec, 0.05, 10),
    fireCount: clampCount(t.fireCount, L.maxFirePerBurst),
    smokeCount: clampCount(t.smokeCount, L.maxSmokePerBurst),
    emberCount: clampCount(t.emberCount, L.maxEmberPerBurst),
    ringSpeedMps: clampNum(t.ringSpeedMps, 0, 400),
    lightIntensity: clampNum(t.lightIntensity, 0, 1000),
    seed: Math.floor(t.seed) >>> 0,
    smokeOpacity: clampNum(t.smokeOpacity, 0, 1),
    ringOpacity: clampNum(t.ringOpacity, 0, 1),
    // 0 collapses the plume into a flat disc at the burst centre, which is a
    // legitimate look and the honest floor for a slider; 8 half-heights leaves
    // the old unclamped ball.
    plumeNeckH: clampNum(t.plumeNeckH, 0, 8),
    plumeCapH: clampNum(t.plumeCapH, 0, 8),
    capFlatten: clampNum(t.capFlatten, 0, 1),
    emberSpeedPerH: clampNum(t.emberSpeedPerH, 0, 40),
    ringReachH: clampNum(t.ringReachH, 0, 40),
    plumeMix: clampNum(t.plumeMix, 0, 1),
    fireCapShare: clampNum(t.fireCapShare, 0, 1),
    capFireFlatten: clampNum(t.capFireFlatten, 0, 1),
    curlStrength: clampNum(t.curlStrength, 0, 2),
    // The fireball is a few metres across; 0.25 m cells is the tightest that
    // still reads as flow rather than noise, and 64 m is the flame cards' own
    // body scale and beyond.
    curlScale: clampNum(t.curlScale, 0.25, 64),
    softFade: clampNum(t.softFade, 0, 2),
  };
}

/**
 * THE WARP'S GRADIENT CAP (explosion-curl cross fix, 2026-09-18; re-measured
 * and tightened the same day after the residue survived the first value).
 *
 * A curl domain warp compresses the noise lookup as its spatial gradient rises
 * toward the lookup's own: the noise coordinate travels `~3.4` across one
 * billboard, while the warp travels about `curlStrength × fieldSlope /
 * curlScale` per world metre. Where the two gradients oppose, the lookup
 * locally compresses (a caustic ridge); the first pass called the extreme case
 * a "fold" and measured its threshold at a warp amplitude of 0.4 at
 * curlScale 2.2 (ratio ≈ 0.18). That measurement was taken by eye on one
 * strength/scale pair and was too generous: with the gate in
 * `scripts/explosion-seam-check.mjs`, the straight-line residue is still
 * FLAGGED at that ratio and only clears lower.
 *
 * MEASURED with the gate (difference of per-row/column edge sums, one fire
 * billboard and the full scenes): the crossed/clean boundary sits at a
 * `strength / curlScale` ratio of about 0.09–0.10, and a single billboard needs
 * the tighter ≈ 0.06 (curlScale 12 is clean for the full ground/clip frames,
 * 18 for the isolated quad). `CURL_WARP_SAFE_RATIO = 0.06` is that measured
 * single-quad bound: at `curlScale >= 1.1 / 0.06 ≈ 18.3` the shipped
 * `curlStrength = 1.1` is applied in full, and below it a tighter swirl gets a
 * proportionally smaller amplitude instead of compressing.
 *
 * The applied amplitude is CAPPED at `CURL_WARP_SAFE_RATIO × curlScale`, so the
 * whole tuning range is compression-free rather than only the shipped values.
 *
 * The TSL side mirrors this expression in {@link explosionLookColor}; keep the
 * two in step.
 */
export const CURL_WARP_SAFE_RATIO = 0.06;

export function curlWarpGain(curlStrength: number, curlScale: number): number {
  if (!(curlStrength > 0) || !(curlScale > 0)) return 0;
  const cap = CURL_WARP_SAFE_RATIO * curlScale;
  return curlStrength < cap ? curlStrength : cap;
}

/** Uniform-ish sample inside the unit ball. Cube-root radius keeps the points
 *  EVEN through the volume rather than clumped at the centre — the difference
 *  between a fireball and a bright dot with stray licks. */
export function randomInUnitSphere(rng: () => number): [number, number, number] {
  const z = rng() * 2 - 1;
  const theta = rng() * TAU;
  const r = Math.cbrt(rng());
  const s = Math.sqrt(Math.max(0, 1 - z * z));
  return [r * s * Math.cos(theta), r * z, r * s * Math.sin(theta)];
}

// ————————————————————————————————————————————————————————————————————————
// The look, in TSL. Everything below runs on the GPU.
// ————————————————————————————————————————————————————————————————————————

export type ExplosionLayer = 'fire' | 'smoke' | 'ember' | 'ring';

/**
 * TSL's published typings model each node as a fixed swizzle view and reject
 * the chained arithmetic a shader is actually written from; the repo casts at
 * call sites instead (bone-instancer.ts:293-295). One alias here keeps the
 * node graph readable — the shapes are erased, the graph is not.
 */
interface Tsl {
  x: Tsl; y: Tsl; z: Tsl; w: Tsl; r: Tsl; g: Tsl; b: Tsl; a: Tsl;
  add(v: Tsl | number): Tsl; sub(v: Tsl | number): Tsl;
  mul(v: Tsl | number): Tsl; div(v: Tsl | number): Tsl;
  abs(): Tsl; pow(v: Tsl | number): Tsl; oneMinus(): Tsl;
  clamp(lo: Tsl | number, hi: Tsl | number): Tsl;
  smoothstep(e0: Tsl | number, e1: Tsl | number): Tsl;
}
/** An opaque TSL node value, for calls into the library functions. */
type N = never;

/** The look graph's uniforms. `time` drives noise advection and the fine
 *  flicker; `gain` is the tuning seam; `curlStrength`/`curlScale` are the
 *  shared curl-volume seam and `softFade` the soft-particle depth fade. The
 *  defaults come from EXPLOSION_VFX_TUNING, so the graph boots on the game's
 *  unchanged look. */
export function makeExplosionLookUniforms() {
  return {
    time: uniform(0),
    gain: uniform(1),
    curlStrength: uniform(EXPLOSION_VFX_TUNING.curlStrength),
    curlScale: uniform(EXPLOSION_VFX_TUNING.curlScale),
    softFade: uniform(EXPLOSION_VFX_TUNING.softFade),
  };
}
export type ExplosionLookUniforms = ReturnType<typeof makeExplosionLookUniforms>;

/**
 * The blackbody-ish ramp the brief asks for, walked the way a real fire is:
 * t = 1 is white-hot, t = 0 is transparent. Five stops, each a `mix` gated by
 * its own `smoothstep` band, so the ramp reads as a continuum rather than four
 * visible steps.
 */
function blackbody(t: Tsl): Tsl {
  const a = mix(vec3(0.42, 0.015, 0) as N, vec3(1.0, 0.11, 0.01) as N,
    smoothstep(0.0, 0.22, t as N) as N) as unknown as Tsl;
  const b = mix(a as N, vec3(1.0, 0.42, 0.04) as N,
    smoothstep(0.22, 0.5, t as N) as N) as unknown as Tsl;
  const c = mix(b as N, vec3(1.0, 0.8, 0.22) as N,
    smoothstep(0.5, 0.78, t as N) as N) as unknown as Tsl;
  return mix(c as N, vec3(1.0, 0.97, 0.88) as N,
    smoothstep(0.78, 1.0, t as N) as N) as unknown as Tsl;
}

/**
 * Build the colour node for one layer. THIS is the whole effect: a fractal
 * noise field advected upward by `time` and offset per billboard by
 * `aBurst.x` (so no two billboards ever carry the same pattern), shaped by a
 * radial falloff into a soft round billboard, and remapped through the
 * blackbody ramp. There is not one texel of image data anywhere.
 *
 * Attribute contract (written by the CPU every frame):
 *   aUv    vec2 — quad-local 0..1. For the ring, x = angle, y = thickness.
 *   aBurst vec4 — (seed, localAge01, heat, glow).
 *     heat  = envelope intensity × per-billboard jitter (the CPU half).
 *     glow  = smoke's internal fire-light / the ring's youth.
 *
 * The blackbody ramp is only used by fire and embers. Smoke and the ring are
 * not hot gas and are shaded directly — smoke from a lit near-black, the ring
 * from a young white-blue front to an old orange one.
 */
export function explosionLookColor(
  layer: ExplosionLayer,
  u: ExplosionLookUniforms,
): Tsl {
  const aUv = attribute('aUv', 'vec2') as unknown as Tsl;
  const aBurst = attribute('aBurst', 'vec4') as unknown as Tsl;
  const seed = aBurst.x;
  const age = aBurst.y;
  const heat = aBurst.z;
  const glow = aBurst.w;

  const isSmoke = layer === 'smoke';
  const isRing = layer === 'ring';
  const isEmber = layer === 'ember';

  // — Quad-local coordinates, −1..1 with (0,0) at the centre. ——————————
  const p = aUv.sub(vec2(0.5) as N).mul(vec2(2.0) as N) as unknown as Tsl;

  // — Noise advection. Fire licks ~5× faster than smoke drifts; the third
  //   axis is a slow "sheet" march so the field is not one flat 2D pattern
  //   stamped onto every billboard in the burst.
  const riseRate = isSmoke ? 0.35 : isEmber ? 2.4 : 1.7;
  const scale = isSmoke ? 2.6 : 3.4;
  // — CURL DOMAIN WARP (fire and smoke only) ——————————————————————————
  // The SHARED divergence-free curl volume (curl-volume-node.ts), sampled at
  // the fragment's WORLD position and time, displaces the fractal-noise lookup
  // so the fireball and the smoke billow and swirl instead of scrolling in one
  // direction. Divergence-free is the point: it reads as flow, not drift, and
  // neighbouring fragments sample neighbouring cells, so the plume moves as one
  // mass. `curlStrength = 0` (the game default) contributes EXACTLY zero — the
  // pre-curl look is unchanged. Ring and embers are not a gas plume, so they
  // keep their own motion and never sample the volume.
  //
  // THE GRADIENT CAP (the cross fix — see curlWarpGain). A domain warp
  // compresses the noise lookup as its spatial gradient rises toward the
  // lookup's own; the extreme case photographed as a straight horizontal streak
  // + a vertical seam through a SINGLE fire quad (NOTES 2026-09-18, both
  // passes). The compression is governed by the warp's gradient, i.e.
  // amplitude / curlScale, so the applied amplitude is capped at
  // `CURL_WARP_SAFE_RATIO * curlScale`. The shipped 18 m scale therefore allows
  // the full strength; a tighter swirl gets a proportionally smaller amplitude
  // instead of compressing. TSL twin of curlWarpGain() — keep in step.
  const curlGain = min(
    u.curlStrength as never,
    (u.curlScale as unknown as Tsl).mul(CURL_WARP_SAFE_RATIO) as never,
  ) as unknown as Tsl;
  const curlWarp = (isSmoke || (!isRing && !isEmber))
    ? (curlVector(
        positionWorld as never,
        u.time as never,
        u.curlScale as never,
      ) as unknown as Tsl).mul(curlGain as never)
    : (vec3(0) as unknown as Tsl);
  const noisePos = vec3(
    aUv.x.mul(scale).add(seed.mul(17.31) as N).add(curlWarp.x as N) as N,
    aUv.y.mul(scale).sub((u.time as N as Tsl).mul(riseRate) as N).add(seed.mul(9.13) as N)
      .add(curlWarp.y as N) as N,
    (u.time as N as Tsl).mul(isSmoke ? 0.1 : 0.5) as N,
  ) as unknown as Tsl;
  const fractal = mx_fractal_noise_float(noisePos as N, isSmoke ? 3 : 2, 2.0, 0.5) as unknown as Tsl;
  const n01 = clamp(fractal.mul(0.5).add(0.5) as N, 0.0, 1.0) as unknown as Tsl;

  if (isRing) {
    // The annulus is thin (uv.y 0..1 across the band) and the noise breaks it
    // into a ragged front rather than a clean hoop.
    const across = float(aUv.y as N).sub(float(0.5)).abs().mul(float(2.0)) as unknown as Tsl;
    const band = float(1).sub(smoothstep(0.0, 1.0, across as N) as N) as unknown as Tsl;
    const hot = mix(vec3(0.9, 0.35, 0.08) as N, vec3(1.0, 0.95, 0.85) as N, glow as N) as unknown as Tsl;
    const coverage = clamp(
      band.mul(n01.mul(0.6).add(0.45) as N).mul(heat as N) as N, 0.0, 1.0,
    ) as unknown as Tsl;
    return vec4(hot.mul(u.gain as N) as N, coverage as N) as unknown as Tsl;
  }

  if (isEmber) {
    // A STREAK, not a dot: uv.x runs along the spark, uv.y across it, so the
    // core is a thin lens and both ends taper.
    const across = p.y;
    const along = p.x;
    const core = float(1).sub(across.abs() as N) as unknown as Tsl;
    const taper = float(1).sub(smoothstep(0.3, 1.0, along.abs() as N) as N) as unknown as Tsl;
    const flicker = n01.mul(0.65).add(0.35) as unknown as Tsl;
    const coverage = clamp(
      core.mul(taper as N).mul(flicker as N).mul(heat as N) as N, 0.0, 1.0,
    ) as unknown as Tsl;
    // Sparks cool white -> yellow -> red across their life; `age` carries the
    // streak's own progress and `flicker` the per-spark noise.
    const rgb = mix(vec3(1.0, 0.28, 0.04) as N, vec3(1.0, 0.86, 0.5) as N,
      flicker.mul(float(1).sub(age as N) as N) as N) as unknown as Tsl;
    return vec4(rgb.mul(u.gain as N) as N, coverage as N) as unknown as Tsl;
  }

  // — Fire and smoke share the SHAPE. Only the shading differs. ————————
  const r = length(p as N) as unknown as Tsl;
  // Soft round coverage. The hard-edged square this whole file exists to
  // avoid would be `coverage = 1` inside the quad and 0 outside; this is the
  // opposite by construction.
  const edge = float(1).sub(smoothstep(0.22, 1.0, r as N) as N) as unknown as Tsl;
  const breakUp = n01.mul(isSmoke ? 0.8 : 1.15).add(isSmoke ? 0.2 : 0.02) as unknown as Tsl;
  const coverage = clamp(edge.mul(breakUp as N) as N, 0.0, 1.0) as unknown as Tsl;

  // — SOFT-PARTICLE DEPTH FADE (soft-fade.ts) —————————————————————————
  // Fire and smoke fade out as they approach the scene surface BEHIND them, so
  // the straight depth-test cut where a quad meets the floor (or a wall) turns
  // into a gradient — the classic explosion-on-a-floor artifact. The helper
  // reads the scene side itself, from `viewportLinearDepth`; only the CURRENT
  // fragment's `linearDepth()` is passed, so the wildfire teardown's
  // `(d - d) / fade = 0` transparent-black trap is unreachable here.
  // `softFade = 0` (the game default) is fully inert.
  const depthFade = softParticleFade(
    linearDepth() as never, u.softFade as never,
  ) as unknown as Tsl;

  if (isSmoke) {
    // Dark, warm, and briefly lit from inside by the fireball it came out of.
    const shade = mix(vec3(0.04, 0.034, 0.032) as N, vec3(0.2, 0.17, 0.16) as N,
      n01 as N) as unknown as Tsl;
    const emberLight = vec3(1.0, 0.3, 0.05).mul(glow.mul(0.7) as N) as unknown as Tsl;
    return vec4(
      shade.add(emberLight as N) as N,
      coverage.mul(heat as N).mul(depthFade as N) as N,
    ) as unknown as Tsl;
  }

  // Fire: hottest in the core, cooled by the noise filaments and by the
  // billboard's own age — so an old lick is deep red before it vanishes.
  const t = clamp(
    float(1).sub(r as N).mul(float(0.85))
      .add(n01.mul(0.5) as N)
      .sub(age.mul(0.4) as N) as N,
    0.0, 1.0,
  ) as unknown as Tsl;
  // Ramp, then the "transparent" end of it: below t ≈ 0.05 the fire is not
  // merely dark, it is GONE — which is what gives the wisps their soft edges.
  const extinction = smoothstep(0.02, 0.22, t as N) as unknown as Tsl;
  const rgb = blackbody(t).mul(extinction as N) as unknown as Tsl;
  return vec4(
    rgb.mul(u.gain as N) as N,
    coverage.mul(heat as N).mul(depthFade as N) as N,
  ) as unknown as Tsl;
}

/**
 * One layer's material. EXPORTED for the spike page's transparency A/B: the
 * `alphaControl` switch builds the exact same node graph through the two
 * material flags this repo has already been burned by, so the failure mode can
 * be photographed next to the working path instead of asserted from memory.
 *
 * depthTest stays ON and depthWrite OFF for every variant: the burst must be
 * occluded by the completed SDF depth buffer and must never occlude itself.
 * Draw order is the caller's business (see createExplosionVfx).
 */
export function createExplosionLookMaterial(
  layer: ExplosionLayer,
  u: ExplosionLookUniforms,
  opts: { alphaControl?: 'none' | 'hash' | 'test' } = {},
): MeshBasicNodeMaterial {
  const material = new MeshBasicNodeMaterial();
  material.colorNode = explosionLookColor(layer, u) as never;
  material.depthTest = true;
  material.depthWrite = false;
  // The burst is added over an already tone-mapped composite; running it
  // through the tone map again would just clip the white-hot core to grey.
  material.toneMapped = false;
  material.side = THREE.DoubleSide;
  material.fog = false;

  const control = opts.alphaControl ?? 'none';
  if (control === 'hash') {
    // THE KNOWN-BAD PATH (blood-view-gpu.ts:154). Reachable only so the spike
    // can prove the difference on this backend.
    material.transparent = false;
    material.alphaHash = true;
  } else if (control === 'test') {
    // The other known-bad-for-glow path: a hard cutout destroys exactly the
    // softness a fireball is made of.
    material.transparent = false;
    material.alphaTest = 0.5;
  } else {
    material.transparent = true;
    // Additive for the three emissive layers, normal for smoke. See the file
    // header for the exact blend factors this produces on WebGPU.
    material.blending = layer === 'smoke' ? THREE.NormalBlending : THREE.AdditiveBlending;
  }
  return material;
}

// ————————————————————————————————————————————————————————————————————————
// CPU-side quad/annulus assembly
// ————————————————————————————————————————————————————————————————————————

/** The 4 corners of a unit quad, CCW, paired with their uv. */
const QUAD_CORNERS: readonly (readonly [number, number, number, number])[] = [
  [-1, -1, 0, 0], [1, -1, 1, 0], [1, 1, 1, 1], [-1, 1, 0, 1],
];

/** One dynamic layer: the geometry the CPU refills, its attributes, and how
 *  many quads are live this frame. */
interface Layer {
  pos: Float32Array;
  uv: Float32Array;
  burst: Float32Array;
  geo: THREE.BufferGeometry;
  mesh: THREE.Mesh;
  count: number;
}

function makeLayer(
  quads: number, material: MeshBasicNodeMaterial, name: string, renderOrder: number,
): Layer {
  const verts = quads * VERTS_PER_QUAD;
  const pos = new Float32Array(verts * 3);
  const uv = new Float32Array(verts * 2);
  const burst = new Float32Array(verts * 4);
  const geo = new THREE.BufferGeometry();
  const posAttr = new THREE.BufferAttribute(pos, 3);
  const uvAttr = new THREE.BufferAttribute(uv, 2);
  const burstAttr = new THREE.BufferAttribute(burst, 4);
  posAttr.setUsage(THREE.DynamicDrawUsage);
  uvAttr.setUsage(THREE.DynamicDrawUsage);
  burstAttr.setUsage(THREE.DynamicDrawUsage);
  geo.setAttribute('position', posAttr);
  geo.setAttribute('aUv', uvAttr);
  geo.setAttribute('aBurst', burstAttr);
  // Unused by MeshBasicNodeMaterial's lighting model, but present so a future
  // normal-reading node cannot fault on a missing vertex buffer.
  geo.setAttribute('normal', new THREE.BufferAttribute(new Float32Array(verts * 3), 3));
  const idx = new Uint32Array(quads * INDICES_PER_QUAD);
  for (let q = 0; q < quads; q++) {
    const v = q * VERTS_PER_QUAD;
    const i = q * INDICES_PER_QUAD;
    idx[i] = v; idx[i + 1] = v + 1; idx[i + 2] = v + 2;
    idx[i + 3] = v; idx[i + 4] = v + 2; idx[i + 5] = v + 3;
  }
  const idxAttr = new THREE.BufferAttribute(idx, 1);
  idxAttr.setUsage(THREE.StaticDrawUsage);
  geo.setIndex(idxAttr);
  geo.setDrawRange(0, 0);
  const mesh = new THREE.Mesh(geo, material);
  mesh.name = name;
  // Vertices are WORLD-space and the mesh never moves, so three's bounding-
  // sphere cull would test a stale sphere and remove the whole effect.
  mesh.frustumCulled = false;
  mesh.renderOrder = renderOrder;
  mesh.visible = false;
  mesh.matrixAutoUpdate = false;
  return { pos, uv, burst, geo, mesh, count: 0 };
}

/**
 * Write one camera-facing quad at quad slot `quad`. `rx`/`ry` are half
 * extents, `roll` rotates the quad inside the billboard plane. This is the
 * module's hot loop — a few hundred calls per frame at absolute worst.
 */
function writeQuad(
  L: Layer, quad: number,
  cx: number, cy: number, cz: number,
  rx: number, ry: number, roll: number,
  rX: number, rY: number, rZ: number,
  uX: number, uY: number, uZ: number,
  seed: number, age: number, heat: number, glow: number,
): void {
  const c = Math.cos(roll);
  const s = Math.sin(roll);
  const vBase = quad * VERTS_PER_QUAD;
  for (let k = 0; k < 4; k++) {
    const corner = QUAD_CORNERS[k]!;
    const ox = corner[0] * rx;
    const oy = corner[1] * ry;
    const lx = ox * c - oy * s;
    const ly = ox * s + oy * c;
    const o = (vBase + k) * 3;
    L.pos[o] = cx + rX * lx + uX * ly;
    L.pos[o + 1] = cy + rY * lx + uY * ly;
    L.pos[o + 2] = cz + rZ * lx + uZ * ly;
    const po = (vBase + k) * 2;
    L.uv[po] = corner[2];
    L.uv[po + 1] = corner[3];
    const bo = (vBase + k) * 4;
    L.burst[bo] = seed;
    L.burst[bo + 1] = age;
    L.burst[bo + 2] = heat;
    L.burst[bo + 3] = glow;
  }
}

/**
 * Write one shockwave annulus as RING_SEGMENTS quads starting at `quad`.
 * `flat` lays it in the world XZ plane (a dome on the floor, seen edge-on);
 * otherwise it lies in the camera plane (an airburst shell, whose silhouette
 * is a circle). The flat case gets its own basis — reusing the camera basis
 * would collapse the annulus into a line.
 */
function writeRing(
  L: Layer, quad: number,
  cx: number, cy: number, cz: number,
  radiusM: number, flat: boolean,
  camRX: number, camRY: number, camRZ: number,
  camUX: number, camUY: number, camUZ: number,
  seed: number, alpha: number, glow: number,
): void {
  const r0 = radiusM * (1 - RING_THICKNESS_FRAC);
  const r1 = radiusM * (1 + RING_THICKNESS_FRAC);
  const rX = flat ? 1 : camRX, rY = flat ? 0 : camRY, rZ = flat ? 0 : camRZ;
  const uX = flat ? 0 : camUX, uY = flat ? 0 : camUY, uZ = flat ? 1 : camUZ;
  for (let sIdx = 0; sIdx < RING_SEGMENTS; sIdx++) {
    const a0 = (sIdx / RING_SEGMENTS) * TAU;
    const a1 = ((sIdx + 1) / RING_SEGMENTS) * TAU;
    const u0 = sIdx / RING_SEGMENTS;
    const u1 = (sIdx + 1) / RING_SEGMENTS;
    const c0 = Math.cos(a0), s0 = Math.sin(a0);
    const c1 = Math.cos(a1), s1 = Math.sin(a1);
    const corners: readonly (readonly [number, number, number, number])[] = [
      [c0 * r0, s0 * r0, u0, 0],
      [c1 * r0, s1 * r0, u1, 0],
      [c1 * r1, s1 * r1, u1, 1],
      [c0 * r1, s0 * r1, u0, 1],
    ];
    const vBase = (quad + sIdx) * VERTS_PER_QUAD;
    for (let k = 0; k < 4; k++) {
      const q = corners[k]!;
      const o = (vBase + k) * 3;
      L.pos[o] = cx + rX * q[0] + uX * q[1];
      L.pos[o + 1] = cy + rY * q[0] + uY * q[1];
      L.pos[o + 2] = cz + rZ * q[0] + uZ * q[1];
      const po = (vBase + k) * 2;
      L.uv[po] = q[2];
      L.uv[po + 1] = q[3];
      const bo = (vBase + k) * 4;
      L.burst[bo] = seed;
      L.burst[bo + 1] = 0;
      L.burst[bo + 2] = alpha;
      L.burst[bo + 3] = glow;
    }
  }
}

// ————————————————————————————————————————————————————————————————————————
// The effect
// ————————————————————————————————————————————————————————————————————————

// Fire/smoke billboard params: dirX,dirY,dirZ, dist, sizeJitter, delay, span,
// roll0, rollSpeed, intensityJitter, role.
// `role` is fire only (0 = the neck, 1 the cap — see capFireEnvelope); smoke
// reads 0 there and ignores it.
const PARTICLE_STRIDE = 11;
/** Fire billboards that ride the cap rather than forming the neck. */
const FIRE_CAP_ROLE = 1;
// Ember params: dirX,dirY,dirZ, speed, halfLen, lifeFrac, seed, intensityJitter.
const EMBER_STRIDE = 8;

interface ExtentAcc {
  count: number;
  min: [number, number, number];
  max: [number, number, number];
  sumY: number;
  ys: number[];
}

function newExtentAcc(): ExtentAcc {
  return {
    count: 0,
    min: [Infinity, Infinity, Infinity],
    max: [-Infinity, -Infinity, -Infinity],
    sumY: 0,
    ys: [],
  };
}

/**
 * Note one emitted quad's DRAWN extent, not just its centre.
 *
 * The distinction matters and it is the difference between two very different
 * answers to "is it a mushroom". A layer's centres can span 0.8 x 0.6 m while
 * the billboards drawn at them are 1.3 m across, so the centre box describes
 * the layout and the drawn box describes the SILHOUETTE — and the silhouette is
 * what the eye compares against the reference.
 *
 * `rx`/`ry` are half-extents in the billboard's own plane. A GROUND burst locks
 * the billboard's up axis to world +Y (see the cylindrical basis in update), so
 * `ry` is exactly vertical and `rx` is exactly horizontal; an airburst's basis
 * is the camera's, which this deliberately does not try to project. Both
 * extents are therefore exact for the ground case the plume exists for, and the
 * z box is written with `rx` on the same "roughly isotropic in xz" footing.
 */
function noteQuad(
  a: ExtentAcc, cx: number, cy: number, cz: number, rx = 0, ry = 0,
): void {
  a.count++;
  if (cx - rx < a.min[0]) a.min[0] = cx - rx;
  if (cy - ry < a.min[1]) a.min[1] = cy - ry;
  if (cz - rx < a.min[2]) a.min[2] = cz - rx;
  if (cx + rx > a.max[0]) a.max[0] = cx + rx;
  if (cy + ry > a.max[1]) a.max[1] = cy + ry;
  if (cz + rx > a.max[2]) a.max[2] = cz + rx;
  a.sumY += cy;
  a.ys.push(cy);
}

/**
 * WHERE A LAYER'S MASS SITS: the mean height of its quads, and the mean height
 * of the bottom and top QUARTILES of them.
 *
 * Pure and exported so it can be tested. The quartiles are the whole point:
 * a bounding-box band split reorders between runs because one stray pixel
 * re-cuts the bands (measured on the frame-differential rig: the same arm read
 * cap/stem 7.45 and then 0.26), while a quartile of the SAMPLE SET cannot move
 * unless the distribution itself moves.
 */
export function extentQuartiles(ys: readonly number[]): {
  meanY: number; lowQuartileY: number; highQuartileY: number;
} {
  if (ys.length === 0) return { meanY: 0, lowQuartileY: 0, highQuartileY: 0 };
  const sorted = [...ys].sort((x, y) => x - y);
  const q = Math.max(1, Math.floor(sorted.length / 4));
  const mean = (arr: number[]) => arr.reduce((m, v) => m + v, 0) / Math.max(1, arr.length);
  return {
    meanY: mean(sorted),
    lowQuartileY: mean(sorted.slice(0, q)),
    highQuartileY: mean(sorted.slice(-q)),
  };
}

/** One layer's accumulated extents, as the seam reports them. */
function extentOf(a: ExtentAcc): LayerExtent {
  if (a.count === 0) {
    return { count: 0, min: [0, 0, 0], max: [0, 0, 0], meanY: 0, lowQuartileY: 0, highQuartileY: 0 };
  }
  return { count: a.count, min: a.min, max: a.max, ...extentQuartiles(a.ys) };
}

export function createExplosionVfx(): ExplosionVfx {
  const L = EXPLOSION_VFX_LIMITS;
  const maxFireQuads = L.maxBursts * L.maxFirePerBurst;
  const maxSmokeQuads = L.maxBursts * L.maxSmokePerBurst;
  const maxEmberQuads = L.maxBursts * L.maxEmberPerBurst;
  const maxRingQuads = L.maxBursts * RING_SEGMENTS;
  const maxEmbers = L.maxBursts * L.maxEmberPerBurst;

  const uniforms = makeExplosionLookUniforms();
  const fire = makeLayer(maxFireQuads, createExplosionLookMaterial('fire', uniforms),
    'ExplosionFire', 1);
  const smoke = makeLayer(maxSmokeQuads, createExplosionLookMaterial('smoke', uniforms),
    'ExplosionSmoke', 0);
  const ember = makeLayer(maxEmberQuads, createExplosionLookMaterial('ember', uniforms),
    'ExplosionEmbers', 2);
  const ring = makeLayer(maxRingQuads, createExplosionLookMaterial('ring', uniforms),
    'ExplosionShockwave', 3);

  const object = new THREE.Group();
  object.name = 'ExplosionVfx';
  // Smoke is painted FIRST, then the emissive layers over it: all four
  // materials have depthWrite off, so this is a pure ordering decision, and
  // dark smoke drawn over a white-hot core would eat the brightest part of
  // the burst.
  object.add(smoke.mesh, fire.mesh, ember.mesh, ring.mesh);
  object.matrixAutoUpdate = false;

  // ——— Pooled state. Allocated here, and never again. —————————————————
  const ages = new Float32Array(L.maxBursts).fill(Infinity);
  const anchors: (BurstAnchor | null)[] = new Array(L.maxBursts).fill(null);
  const slotSeed = new Float32Array(L.maxBursts);
  const fireCounts = new Uint8Array(L.maxBursts);
  const smokeCounts = new Uint8Array(L.maxBursts);
  const emberCounts = new Uint8Array(L.maxBursts);
  const ringLive = new Uint8Array(L.maxBursts);
  const fireParams = new Float32Array(L.maxBursts * L.maxFirePerBurst * PARTICLE_STRIDE);
  const smokeParams = new Float32Array(L.maxBursts * L.maxSmokePerBurst * PARTICLE_STRIDE);
  const emberParams = new Float32Array(maxEmbers * EMBER_STRIDE);
  const embers: EmberState[] = Array.from(
    { length: maxEmbers },
    () => ({ px: 0, py: 0, pz: 0, vx: 0, vy: 0, vz: 0 }),
  );

  const tuning: ExplosionVfxTuning = { ...EXPLOSION_VFX_TUNING };
  // Push the tuning's look switches into the material uniforms. Called once at
  // construction (so the graph boots on the shipped defaults) and on every
  // setTuning. The uniform factory also defaults to EXPLOSION_VFX_TUNING, so
  // this is a belt-and-braces sync, not the only source of the default.
  const syncLookUniforms = (): void => {
    uniforms.gain.value = tuning.gain;
    uniforms.curlStrength.value = tuning.curlStrength;
    uniforms.curlScale.value = tuning.curlScale;
    uniforms.softFade.value = tuning.softFade;
  };
  syncLookUniforms();
  let sequence = 0;
  let simTime = 0;
  let peakLight = 0;
  /**
   * THIS FRAME'S EMITTED SHAPE, per layer (see ExplosionVfx.layerExtents).
   * Accumulated by `noteQuad` at the two emit sites and reset at the top of
   * every `update()`. Deliberately cheap: a few adds per quad, and it is the
   * measurement that says whether the plume is a mushroom or a pancake without
   * a GPU readback or a bounding box.
   */
  const extentAcc = {
    fire: newExtentAcc(), smoke: newExtentAcc(), ember: newExtentAcc(), ring: newExtentAcc(),
  };
  let extentHalfHeight = 0;

  const camRight = new THREE.Vector3();
  const camUp = new THREE.Vector3();
  const toCam = new THREE.Vector3();

  /** A stable per-billboard noise seed. Constant for the life of the burst,
   *  so the GPU's noise field does not reshuffle between frames. */
  function noiseSeedOf(slot: number, i: number): number {
    return (((slot * 97 + i) * 0.6180339887) % 1) * 90 + slotSeed[slot]! * 0.001;
  }

  function spawnFireParams(slot: number, count: number, rng: () => number): void {
    const base = slot * L.maxFirePerBurst * PARTICLE_STRIDE;
    for (let i = 0; i < count; i++) {
      const o = base + i * PARTICLE_STRIDE;
      const dir = randomInUnitSphere(rng);
      fireParams[o] = dir[0];
      fireParams[o + 1] = dir[1];
      fireParams[o + 2] = dir[2];
      fireParams[o + 3] = 0.15 + 0.55 * rng();
      fireParams[o + 4] = 0.7 + 0.6 * rng();
      // Stagger. Fourteen identical quads pulsing together do not read as
      // fire. Kept SHORT: a detonation has to be visibly hot within two frames
      // of spawn, not a fifth of a second later.
      fireParams[o + 5] = 0.05 * rng();
      fireParams[o + 6] = 0.75 + 0.3 * rng();
      fireParams[o + 7] = rng() * TAU;
      fireParams[o + 8] = (rng() - 0.5) * 1.8;
      fireParams[o + 9] = 0.65 + 0.6 * rng();
      // THE ROLE, drawn before the spawn offsets that depend on it so the rng
      // sequence stays a straight line.
      const cap = rng() < tuning.fireCapShare ? FIRE_CAP_ROLE : 0;
      fireParams[o + 10] = cap;
      if (cap === FIRE_CAP_ROLE) {
        // The cap starts OUT on the rim it is about to roll along, not on the
        // axis it would have to climb out of.
        fireParams[o + 3] = 0.35 + 0.6 * rng();
        // ...a touch later than the column, and it lives longer.
        fireParams[o + 5] = 0.12 + 0.1 * rng();
        fireParams[o + 6] = 0.8 + 0.3 * rng();
      }
    }
  }

  function spawnSmokeParams(slot: number, count: number, rng: () => number): void {
    const base = slot * L.maxSmokePerBurst * PARTICLE_STRIDE;
    for (let i = 0; i < count; i++) {
      const o = base + i * PARTICLE_STRIDE;
      // THE CAP IS A RIM, NOT A BALL. A uniform-in-the-ball direction puts most
      // billboards near the middle (volume ∝ r³) whatever the envelope does to
      // the size, so the cloud stays centre-weighted and reads as a sphere. The
      // azimuth goes on the UNIT CIRCLE — every cap billboard is on the outside
      // of the roll — and the vertical component stays small because the
      // envelope's `rise` is what lifts the cap, not the spawn offset.
      const sphere = randomInUnitSphere(rng);
      const theta = rng() * TAU;
      const rxz = 0.75 + 0.25 * rng();
      const rimY = (rng() - 0.5) * 0.6;
      const mix = tuning.plumeMix;
      smokeParams[o] = sphere[0] + (Math.cos(theta) * rxz - sphere[0]) * mix;
      smokeParams[o + 1] = sphere[1] + (rimY - sphere[1]) * mix;
      smokeParams[o + 2] = sphere[2] + (Math.sin(theta) * rxz - sphere[2]) * mix;
      smokeParams[o + 3] = 0.25 + 0.75 * rng();
      smokeParams[o + 4] = 0.75 + 0.7 * rng();
      // Smoke is a LATE bloomer: it starts well after the fire and is still
      // climbing when the fire is out.
      smokeParams[o + 5] = 0.2 + 0.35 * rng();
      smokeParams[o + 6] = 0.5 + 0.4 * rng();
      smokeParams[o + 7] = rng() * TAU;
      smokeParams[o + 8] = (rng() - 0.5) * 0.5;
      smokeParams[o + 9] = 0.7 + 0.6 * rng();
    }
  }

  function spawnEmberParams(slot: number, count: number, rng: () => number): void {
    const base = slot * L.maxEmberPerBurst * EMBER_STRIDE;
    const origin = anchors[slot]!;
    for (let i = 0; i < count; i++) {
      const o = base + i * EMBER_STRIDE;
      const dir = randomInUnitSphere(rng);
      // Biased upward: sparks are thrown by a blast, they do not spray evenly.
      const dy = 0.25 + 0.7 * Math.abs(dir[1]);
      emberParams[o] = dir[0];
      emberParams[o + 1] = dy;
      emberParams[o + 2] = dir[2];
      // Speed in HALF-HEIGHTS per second (tuning.emberSpeedPerH), not absolute
      // m/s: at the old 3.5-14.5 m/s a spark crossed ~4 m — eleven times the
      // half-height of the plume it was thrown out of — so the sparks were
      // their own effect at a scale nothing else in the burst used.
      emberParams[o + 3] = tuning.emberSpeedPerH * (0.55 + 1.45 * rng()) * origin.halfHeightM;
      emberParams[o + 4] = 0.1 + 0.11 * rng();
      emberParams[o + 5] = 0.3 + 0.55 * rng();
      emberParams[o + 6] = noiseSeedOf(slot, i);
      emberParams[o + 7] = 0.6 + 0.7 * rng();
      // Reset the pooled ember here — never reallocated, never stepped while
      // its burst is dead.
      const e = embers[slot * L.maxEmberPerBurst + i]!;
      const speed = emberParams[o + 3]!;
      e.px = origin.at[0];
      e.py = origin.centreY;
      e.pz = origin.at[2];
      e.vx = dir[0] * speed;
      e.vy = dy * speed;
      e.vz = dir[2] * speed;
    }
  }

  /** Emit one particle layer (fire or smoke) for one burst. */
  function emitParticles(
    layer: 'fire' | 'smoke',
    buffers: Layer,
    params: Float32Array,
    slot: number,
    count: number,
    a: BurstAnchor,
    lifeSec: number,
    rX: number, rY: number, rZ: number,
    uX: number, uY: number, uZ: number,
  ): number {
    const cap = layer === 'fire' ? L.maxFirePerBurst : L.maxSmokePerBurst;
    const base = slot * cap * PARTICLE_STRIDE;
    const baseSize = layer === 'fire' ? FIRE_BASE_SIZE : SMOKE_BASE_SIZE;
    const age = ages[slot]!;
    let written = 0;
    for (let i = 0; i < count; i++) {
      const o = base + i * PARTICLE_STRIDE;
      const t = (age / lifeSec - params[o + 5]!) / params[o + 6]!;
      if (t <= 0 || t >= 1) continue;
      let intensity: number;
      let radius: number;
      let rise: number;
      let stretchY: number;
      let flare: number;
      let flatten = 1;
      let glow = 0;
      if (layer === 'fire') {
        const s = params[o + 10] === FIRE_CAP_ROLE
          ? capFireEnvelope(t, tuning.plumeCapH, tuning.capFireFlatten)
          : fireEnvelope(t, tuning.plumeNeckH);
        intensity = s.intensity; radius = s.radius; rise = s.rise;
        stretchY = s.stretchY; flare = s.flare; flatten = s.flatten;
      } else {
        const s = smokeEnvelope(t, tuning.plumeCapH, tuning.capFlatten);
        intensity = s.density * tuning.smokeOpacity;
        radius = s.radius;
        rise = s.rise;
        flare = s.flare;
        flatten = s.flatten;
        // Wider than tall is the CAP's job alone; the neck keeps the brief's
        // "bloom then stretch upward" (stretchY >= 1) that the fire test pins.
        stretchY = 1 + 0.5 * t;
        glow = s.glow;
      }
      // plumeMix = 0 restores the terms' pre-plume constant: a self-similar
      // spread and a round quad.
      const pm = tuning.plumeMix;
      flare = 1 + (flare - 1) * pm;
      flatten = 1 + (flatten - 1) * pm;
      intensity *= params[o + 9]!;
      if (intensity <= 0.002) continue;

      // HORIZONTAL AND VERTICAL ARE SEPARATE TERMS NOW. They used to be one
      // `spread` factor feeding x, z AND y, which makes every billboard's
      // displacement self-similar — a sphere growing about its own centre, at
      // any size and any count. The horizontal term carries the layer's own
      // flare (the neck converges, the cap rolls out) and the vertical one is
      // the spawn jitter the envelope's `rise` climbs on top of.
      const spread = a.halfHeightM * params[o + 3]! * (0.5 + 0.65 * radius) * flare;
      const cx = a.at[0] + params[o]! * spread;
      const cz = a.at[2] + params[o + 2]! * spread;
      const cy = a.centreY + params[o + 1]! * spread * 0.8 + rise * a.halfHeightM;
      const radiusM = a.halfHeightM * baseSize * params[o + 4]! * radius;
      const roll = params[o + 7]! + params[o + 8]! * age;
      noteQuad(extentAcc[layer], cx, cy, cz, radiusM, radiusM * stretchY * flatten);
      if (a.halfHeightM > extentHalfHeight) extentHalfHeight = a.halfHeightM;
      writeQuad(
        buffers, written, cx, cy, cz, radiusM, radiusM * stretchY * flatten, roll,
        rX, rY, rZ, uX, uY, uZ,
        noiseSeedOf(slot, i), t, intensity, glow,
      );
      written++;
    }
    return written;
  }

  const api: ExplosionVfx = {
    object,

    get layerExtents() {
      return {
        fire: extentOf(extentAcc.fire), smoke: extentOf(extentAcc.smoke),
        ember: extentOf(extentAcc.ember), ring: extentOf(extentAcc.ring),
      };
    },
    /** Read from the LIVE bursts' anchors rather than from what they happened
     *  to emit: a freshly spawned burst has emitted nothing yet, and its
     *  half-height is exactly the number a caller needs to read its extents
     *  against. */
    get burstHalfHeightM() {
      let h = 0;
      for (let i = 0; i < L.maxBursts; i++) {
        const a = anchors[i];
        if (a && ages[i]! < tuning.lifeSec && a.halfHeightM > h) h = a.halfHeightM;
      }
      return h || extentHalfHeight;
    },

    get activeBursts(): number {
      let n = 0;
      for (let s = 0; s < L.maxBursts; s++) if (ages[s]! < tuning.lifeSec) n++;
      return n;
    },

    get lightIntensity(): number {
      return peakLight;
    },

    get tuning(): ExplosionVfxTuning {
      return tuning;
    },

    setTuning(patch: Partial<ExplosionVfxTuning>): void {
      Object.assign(tuning, clampTuning({ ...tuning, ...patch }));
      syncLookUniforms();
    },

    spawn(visual: BurstVisual, seed?: number): void {
      const slot = findFreeSlot(ages, tuning.lifeSec);
      const s = burstSeed(seed, sequence++, tuning.seed);
      const burstRng = mulberry32(s);
      slotSeed[slot] = s % 1024;
      const halfH = tuning.fireScale * visual.heightM;
      anchors[slot] = burstAnchor(visual.kind, visual.at, halfH);
      ages[slot] = 0;
      const fireN = clampCount(tuning.fireCount, L.maxFirePerBurst);
      const smokeN = clampCount(tuning.smokeCount, L.maxSmokePerBurst);
      const emberN = clampCount(tuning.emberCount, L.maxEmberPerBurst);
      fireCounts[slot] = fireN;
      smokeCounts[slot] = smokeN;
      emberCounts[slot] = emberN;
      ringLive[slot] = tuning.ringOpacity > 0 ? 1 : 0;
      spawnFireParams(slot, fireN, burstRng);
      spawnSmokeParams(slot, smokeN, burstRng);
      spawnEmberParams(slot, emberN, burstRng);
    },

    update(dtSec: number, camera: THREE.Camera): void {
      const dt = dtSec > 0 ? Math.min(dtSec, MAX_UPDATE_STEP_SEC) : 0;
      simTime += dt;
      uniforms.time.value = simTime;

      // The camera basis drives every billboard. three refreshes the camera's
      // world matrix at RENDER time, which is after this call, so do it here —
      // otherwise every billboard faces last frame's camera and the effect
      // swims whenever the player turns.
      camera.updateMatrixWorld();
      camRight.setFromMatrixColumn(camera.matrixWorld, 0).normalize();
      camUp.setFromMatrixColumn(camera.matrixWorld, 1).normalize();

      fire.count = 0;
      smoke.count = 0;
      ember.count = 0;
      ring.count = 0;
      for (const k of ['fire', 'smoke', 'ember', 'ring'] as const) {
        extentAcc[k] = newExtentAcc();
      }
      extentHalfHeight = 0;
      let peak = 0;

      const life = tuning.lifeSec;
      const ringLife = life * RING_LIFE_FRAC;
      const emberLife = life * EMBER_LIFE_FRAC;

      for (let slot = 0; slot < L.maxBursts; slot++) {
        if (!(ages[slot]! < life)) { ages[slot] = Infinity; anchors[slot] = null; continue; }
        ages[slot] = ages[slot]! + dt;
        const still = ages[slot]!;
        if (!(still < life)) { ages[slot] = Infinity; anchors[slot] = null; continue; }
        const a = anchors[slot]!;
        const u = still / life;

        // — Billboard basis. A ground burst gets a CYLINDRICAL billboard (up
        //   locked to world +Y) so its plume climbs the screen; an airburst
        //   gets the full camera basis, which is what makes a fireball read
        //   as a ball rather than a disc.
        let rX = camRight.x, rY = camRight.y, rZ = camRight.z;
        let uX = camUp.x, uY = camUp.y, uZ = camUp.z;
        if (a.orient === 'plume') {
          toCam.set(
            camera.position.x - a.at[0],
            0,
            camera.position.z - a.at[2],
          );
          const horiz = Math.hypot(toCam.x, toCam.z);
          if (horiz > 1e-4) {
            // right = normalize(cross(worldUp, toCamera)), so the quad's
            // front face looks back at the camera.
            rX = toCam.z / horiz; rY = 0; rZ = -toCam.x / horiz;
          } else {
            rX = 1; rY = 0; rZ = 0;
          }
          uX = 0; uY = 1; uZ = 0;
        }

        fire.count += emitParticles(
          'fire', fire, fireParams, slot, fireCounts[slot]!,
          a, life, rX, rY, rZ, uX, uY, uZ,
        );
        smoke.count += emitParticles(
          'smoke', smoke, smokeParams, slot, smokeCounts[slot]!,
          a, life, rX, rY, rZ, uX, uY, uZ,
        );

        // — Embers: CPU-stepped, pooled, no allocation. ————————————————
        const eBase = slot * L.maxEmberPerBurst;
        for (let i = 0; i < emberCounts[slot]!; i++) {
          const idx = eBase + i;
          const o = idx * EMBER_STRIDE;
          const localU = still / (emberLife * emberParams[o + 5]!);
          if (localU >= 1) continue;
          const e = embers[idx]!;
          stepEmber(e, dt, EMBER_GRAVITY_MPS2, EMBER_DRAG);
          const heat = Math.pow(1 - localU, 1.6) * emberParams[o + 7]!;
          if (heat <= 0.004) continue;
          // The streak lies along the ember's screen-space velocity.
          const speed = Math.hypot(e.vx, e.vy, e.vz);
          const along = speed > 1e-3 ? Math.atan2(
            e.vx * uX + e.vy * uY + e.vz * uZ,
            e.vx * rX + e.vy * rY + e.vz * rZ,
          ) : 0;
          const halfLen = a.halfHeightM * emberParams[o + 4]! * (0.6 + 0.7 * heat);
          noteQuad(extentAcc.ember, e.px, e.py, e.pz, halfLen, halfLen * 0.16);
          writeQuad(
            ember, ember.count, e.px, e.py, e.pz,
            halfLen, halfLen * 0.16, along,
            rX, rY, rZ, uX, uY, uZ,
            emberParams[o + 6]!, localU, heat, 0,
          );
          ember.count++;
        }

        // — Shockwave. ————————————————————————————————————————————————
        if (ringLive[slot]! && u < RING_LIFE_FRAC) {
          const ru = u / RING_LIFE_FRAC;
          const rs = ringEnvelope(
            ru, RING_START_FRAC * a.halfHeightM, tuning.ringSpeedMps, ringLife,
          );
          const alpha = rs.alpha * tuning.ringOpacity;
          // The front stops growing at the plume's own scale (see ringReachH)
          // and fades where it stands — a wall of air that has run out of
          // explosion, not one still accelerating across the room.
          const ringRadius = Math.min(rs.radiusM, tuning.ringReachH * a.halfHeightM);
          if (alpha > 0.004) {
            const flat = a.ring === 'flat';
            // One sample per RING, and at its FRONT rather than its centre:
            // 48 segments of the same circle would swamp the quartiles, and the
            // ring's radius is the thing the shape question asks about.
            // Sampled at ONE point on the front, in +z: the ring is a circle, so
            // its radius is what the box should carry, not 48 samples of the
            // same circumference.
            noteQuad(extentAcc.ring, a.at[0], flat ? a.at[1] : a.centreY, a.at[2] + ringRadius,
              ringRadius, 0);
            if (a.halfHeightM > extentHalfHeight) extentHalfHeight = a.halfHeightM;
            writeRing(
              ring, ring.count,
              a.at[0], flat ? a.at[1] : a.centreY, a.at[2],
              ringRadius, flat, rX, rY, rZ, uX, uY, uZ,
              noiseSeedOf(slot, 0), alpha, 1 - ru,
            );
            ring.count += RING_SEGMENTS;
          }
        }

        const light = lightEnvelope(u) * tuning.lightIntensity;
        if (light > peak) peak = light;
      }

      peakLight = peak;

      for (const layer of [smoke, fire, ember, ring]) {
        layer.geo.setDrawRange(0, layer.count * INDICES_PER_QUAD);
        layer.mesh.visible = layer.count > 0;
        if (layer.count > 0) {
          (layer.geo.getAttribute('position') as THREE.BufferAttribute).needsUpdate = true;
          (layer.geo.getAttribute('aUv') as THREE.BufferAttribute).needsUpdate = true;
          (layer.geo.getAttribute('aBurst') as THREE.BufferAttribute).needsUpdate = true;
        }
      }
    },

    dispose(): void {
      object.removeFromParent();
      for (const layer of [fire, smoke, ember, ring]) {
        layer.geo.dispose();
        (layer.mesh.material as THREE.Material).dispose();
      }
    },
  };

  return api;
}
