// GENERATED by scripts/gait-from-clip.ts from docs/dev-notes/refs/soldier-mesh/zombie-biped-running.glb — do not edit.
// 32 samples over one cycle, phase 0 = left heel strike, angles in
// radians, lengths / leg length. Regenerate: npm run gait:curves -- docs/dev-notes/refs/soldier-mesh/zombie-biped-running.glb soldier-run
import type { GaitCurves } from '../gait-curves';

export const SOLDIER_RUN: GaitCurves = {
  name: 'soldier-run',
  n: 32,
  freq: 1.50000,
  travel: 0.79792,
  hipsY: [0.0035, 0.0190, 0.0298, 0.0345, 0.0354, 0.0237, 0.0117, -0.0005, -0.0113, -0.0223, -0.0358, -0.0425, -0.0445, -0.0391, -0.0279, -0.0082, 0.0096, 0.0263, 0.0403, 0.0451, 0.0437, 0.0322, 0.0197, 0.0056, -0.0045, -0.0132, -0.0199, -0.0239, -0.0261, -0.0261, -0.0221, -0.0119],
  L: { thigh: [0.8041, 0.7770, 0.7032, 0.6299, 0.5572, 0.5097, 0.4802, 0.4734, 0.4183, 0.3311, 0.1652, -0.0140, -0.2024, -1.0231, -0.5841, -0.6730, -0.6978, -0.6936, -0.6364, -0.5856, -0.5391, -0.2849, -0.3899, -0.3142, -0.1676, 0.0118, 0.2490, 0.4416, 0.6036, 0.6036, 0.6571, 0.7898], knee: [1.5344, 1.2287, 0.9079, 0.6389, 0.4008, 0.3327, 0.3577, 0.5249, 0.6472, 0.7304, 0.6959, 0.6315, 0.5526, 0.3343, 0.2803, 0.3103, 0.4674, 0.6721, 0.9446, 1.2016, 1.4491, 1.7039, 1.9482, 2.1750, 2.3218, 2.4320, 2.4651, 2.3698, 2.1875, 2.1875, 2.0852, 1.8279], stance: [false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false] },
  R: { thigh: [-0.5638, -0.5864, -0.5843, -0.5431, -0.4766, -0.1848, -0.2890, -0.1726, 0.0313, 0.2662, 0.5343, 0.6912, 0.7743, 0.8303, 0.8700, 0.8858, 0.8454, 0.7773, 0.6557, 0.5715, 0.5123, 0.4437, 0.4172, 0.4560, 0.4056, 0.3227, 0.1933, 0.0064, -0.2198, -0.2198, -0.0681, -0.5913], knee: [0.2817, 0.4170, 0.6140, 0.8635, 1.1481, 1.4488, 1.7362, 2.0173, 2.2611, 2.4614, 2.5208, 2.4578, 2.3121, 2.1251, 1.9121, 1.6601, 1.3604, 1.0368, 0.6512, 0.3514, 0.1046, 0.0362, 0.1340, 0.4889, 0.6607, 0.7651, 0.7791, 0.6854, 0.5206, 0.5206, 0.4376, 0.2277], stance: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false] },
};
