// GENERATED by scripts/gait-from-clip.ts from docs/dev-notes/refs/soldier-mesh/soldier.glb — do not edit.
// 32 samples over one cycle, phase 0 = left heel strike, angles in
// radians, lengths / leg length. Regenerate: npm run gait:curves -- docs/dev-notes/refs/soldier-mesh/soldier.glb soldier-walk
import type { GaitCurves } from '../gait-curves';

export const SOLDIER_WALK: GaitCurves = {
  name: 'soldier-walk',
  n: 32,
  freq: 0.93750,
  travel: 0.88768,
  hipsY: [-0.0408, -0.0403, -0.0325, -0.0167, 0.0012, 0.0159, 0.0279, 0.0336, 0.0330, 0.0281, 0.0157, 0.0024, -0.0137, -0.0254, -0.0330, -0.0395, -0.0371, -0.0279, -0.0130, 0.0059, 0.0254, 0.0422, 0.0422, 0.0510, 0.0508, 0.0388, 0.0197, -0.0014, -0.0182, -0.0287, -0.0311, -0.0344],
  L: { thigh: [0.6246, 0.6053, 0.5562, 0.4779, 0.3835, 0.2839, 0.1753, 0.0702, -0.0292, -0.1307, -0.2104, -0.3145, -0.3982, -0.4599, -0.4748, -0.3413, -0.1936, -0.0327, 0.1170, 0.2409, 0.3398, 0.4068, 0.4068, 0.4324, 0.4068, 0.4408, 0.5123, 0.5991, 0.6118, 0.5845, 0.5469, 0.5796], knee: [0.7101, 0.8128, 0.8498, 0.8255, 0.7655, 0.6959, 0.6087, 0.5243, 0.4523, 0.3774, 0.3485, 0.2668, 0.2340, 0.2410, 0.3081, 0.6327, 0.9189, 1.1669, 1.3097, 1.3308, 1.2615, 1.1124, 1.1124, 0.8826, 0.5573, 0.3593, 0.2708, 0.2955, 0.3072, 0.3187, 0.3292, 0.4809], stance: [true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true] },
  R: { thigh: [-0.2866, -0.1283, 0.0353, 0.1873, 0.3234, 0.4473, 0.5554, 0.6466, 0.7088, 0.7090, 0.6447, 0.5190, 0.5302, 0.5730, 0.6360, 0.6454, 0.6118, 0.5577, 0.4842, 0.3890, 0.2789, 0.1584, 0.1584, 0.0434, -0.0412, -0.0820, -0.1271, -0.1862, -0.2518, -0.3274, -0.4234, -0.4113], knee: [0.7278, 1.0223, 1.2565, 1.3762, 1.4089, 1.3981, 1.3414, 1.2388, 1.0788, 0.8359, 0.5678, 0.2530, 0.2920, 0.4295, 0.6372, 0.7588, 0.8286, 0.8466, 0.8193, 0.7519, 0.6505, 0.5221, 0.5221, 0.4125, 0.3577, 0.3898, 0.4215, 0.4322, 0.4269, 0.4066, 0.3355, 0.4465], stance: [false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false] },
};
