// GENERATED by scripts/gait-from-clip.ts from docs/dev-notes/refs/helmetsoldier/Meshy_AI_Take_the_soldier_char_biped_Animation_Running_withSkin.glb — do not edit.
// 32 samples over one cycle, phase 0 = left heel strike, angles in
// radians, lengths / leg length. Regenerate: npm run gait:curves -- docs/dev-notes/refs/helmetsoldier/Meshy_AI_Take_the_soldier_char_biped_Animation_Running_withSkin.glb soldier-run
import type { GaitCurves } from '../gait-curves';

export const SOLDIER_RUN: GaitCurves = {
  name: 'soldier-run',
  n: 32,
  freq: 1.50000,
  travel: 0.66307,
  hipsY: [0.0146, 0.0306, 0.0394, 0.0410, 0.0378, 0.0207, 0.0043, -0.0108, -0.0223, -0.0326, -0.0422, -0.0447, -0.0423, -0.0332, -0.0190, 0.0028, 0.0191, 0.0329, 0.0423, 0.0439, 0.0404, 0.0270, 0.0125, -0.0036, -0.0134, -0.0210, -0.0264, -0.0271, -0.0246, -0.0246, -0.0184, -0.0028],
  L: { thigh: [0.8192, 0.7951, 0.7167, 0.6368, 0.5561, 0.5021, 0.4718, 0.4726, 0.4146, 0.3213, 0.1472, -0.0357, -0.2242, -0.4456, -0.6101, -0.6925, -0.7030, -0.6842, -0.6212, -0.5676, -0.5206, -0.4487, -0.3812, -0.3180, -0.1830, -0.0121, 0.2274, 0.4260, 0.5963, 0.5963, 0.6544, 0.7985], knee: [1.6466, 1.3523, 1.0311, 0.7556, 0.5067, 0.4298, 0.4531, 0.6305, 0.7525, 0.8308, 0.7847, 0.7114, 0.6256, 0.4348, 0.3371, 0.3646, 0.5303, 0.7412, 1.0099, 1.2645, 1.5108, 1.7640, 2.0040, 2.2256, 2.3670, 2.4741, 2.5147, 2.4293, 2.2589, 2.2589, 2.1638, 1.9252], stance: [false, false, false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false] },
  R: { thigh: [-0.5644, -0.5815, -0.5723, -0.5271, -0.4587, -0.3728, -0.2782, -0.1713, 0.0216, 0.2481, 0.5201, 0.6845, 0.7776, 0.8393, 0.8840, 0.9036, 0.8644, 0.7960, 0.6710, 0.5818, 0.5164, 0.4426, 0.4178, 0.4687, 0.4187, 0.3324, 0.1980, 0.0048, -0.2282, -0.2282, -0.3075, -0.5060], knee: [0.3633, 0.4952, 0.6906, 0.9380, 1.2204, 1.5167, 1.8020, 2.0756, 2.3117, 2.5084, 2.5815, 2.5337, 2.4049, 2.2290, 2.0271, 1.7855, 1.4937, 1.1747, 0.7847, 0.4756, 0.2166, 0.1362, 0.2345, 0.6112, 0.7850, 0.8857, 0.8934, 0.7911, 0.6164, 0.6164, 0.5304, 0.3139], stance: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false, false, false, false] },
};
