// GENERATED by scripts/distill-theme-data.mjs — do not edit by hand.
// Source: public/assets/map-research/patterns.json (39 maps, 32903 sectors).

export interface ThemeRecord {
  id: string;
  name: string;
  index: number;            // stable cosmetic-RNG fork index
  sourceMaps: string[];
  propPer100Cells: number;  // props per 100 open cells
  rubblePer100Cells: number;
  materialSetId: string;
}

export const THEMES: Record<string, ThemeRecord> = {
  "bb": {
    "id": "bb",
    "name": "Blood BB",
    "index": 0,
    "sourceMaps": [
      "DWBB1",
      "DWBB2",
      "DWBB3"
    ],
    "propPer100Cells": 5,
    "rubblePer100Cells": 3,
    "materialSetId": "bb"
  },
  "e1": {
    "id": "e1",
    "name": "Blood E1",
    "index": 1,
    "sourceMaps": [
      "DWE1M1",
      "DWE1M10",
      "DWE1M11",
      "DWE1M12",
      "DWE1M2",
      "DWE1M3",
      "DWE1M4",
      "DWE1M5",
      "DWE1M6",
      "DWE1M7",
      "DWE1M8",
      "DWE1M9"
    ],
    "propPer100Cells": 8,
    "rubblePer100Cells": 4,
    "materialSetId": "e1"
  },
  "e2": {
    "id": "e2",
    "name": "Blood E2",
    "index": 2,
    "sourceMaps": [
      "DWE2M1",
      "DWE2M10",
      "DWE2M11",
      "DWE2M12",
      "DWE2M2",
      "DWE2M3",
      "DWE2M4",
      "DWE2M5",
      "DWE2M6",
      "DWE2M7",
      "DWE2M8",
      "DWE2M9"
    ],
    "propPer100Cells": 7,
    "rubblePer100Cells": 3,
    "materialSetId": "e2"
  },
  "e3": {
    "id": "e3",
    "name": "Blood E3",
    "index": 3,
    "sourceMaps": [
      "DWE3M1",
      "DWE3M10",
      "DWE3M11",
      "DWE3M12",
      "DWE3M2",
      "DWE3M3",
      "DWE3M4",
      "DWE3M5",
      "DWE3M6",
      "DWE3M7",
      "DWE3M8",
      "DWE3M9"
    ],
    "propPer100Cells": 8,
    "rubblePer100Cells": 4,
    "materialSetId": "e3"
  },
};

export type ThemeId = keyof typeof THEMES & string;
export const DEFAULT_THEME: ThemeId = "bb";
