// GENERATED by scripts/pose_measure_hands.py -- do not edit by hand.
//
// MEASUREMENTS of a real posed hand mesh, in metres. These numbers are FACTS
// derived from a rigged reference model; the model itself is NOT redistributed
// and no part of it lives in this repository.
//
//   Reference: "First Person hands rigged" by DavidFischer (Sketchfab),
//   licensed CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/).
//   Adaptations must credit the author; see public/assets/lab/hand-detail.json
//   for the verbatim attribution line that ships with the derived height maps.
//
// LOCAL FRAME (each hand has its own; both are right-handed):
//   O  = the point on the prop's axis where the hand closes on it
//        (for `pinch`, the pinch point between index and middle)
//   +Z = along the prop axis, toward the prop's business end
//        (`grip`: up out of the fist;  `pinch`: toward the lit end)
//   +X = the back-of-hand outward normal (pointing away from the palm)
//   +Y = Z x X
//
// Because `grip` is a RIGHT hand and `pinch` is a LEFT hand, +Y points toward
// opposite anatomical sides in the two frames -- see the dev note
// docs/dev-notes/2026-08-17-hand-detail-bake.md before mirroring anything.
//
// Each segment is a capsule: `a` and `b` are the axis endpoints and `radius` is
// the MEAN distance from that axis to the mesh surface over the segment.

export interface MeasuredSegment {
  a: readonly [number, number, number];
  b: readonly [number, number, number];
  radius: number;
}

export interface MeasuredHand {
  propRadius: number;
  knuckleSpanM: number;
  segments: Record<string, MeasuredSegment>;
}

export const MEASURED_HANDS: { grip: MeasuredHand; pinch: MeasuredHand } = {
  grip: {
    propRadius: 0.03000,
    knuckleSpanM: 0.08500,
    segments: {
      forearm: { a: [0.04764, -0.09710, -0.01514] as const, b: [0.01050, -0.34021, -0.06007] as const, radius: 0.03977 },
      wrist: { a: [0.04764, -0.09710, -0.01514] as const, b: [0.04525, -0.05024, -0.01254] as const, radius: 0.03135 },
      fist: { a: [0.04525, -0.05024, -0.01254] as const, b: [0.04319, 0.02585, 0.00646] as const, radius: 0.03351 },
      knuckleRidge: { a: [0.04762, 0.02262, 0.05040] as const, b: [0.03637, 0.02238, -0.03460] as const, radius: 0.01381 },
      fingerWrap: { a: [0.00207, 0.03892, 0.04797] as const, b: [0.00334, 0.03787, -0.02987] as const, radius: 0.01326 },
      fingerTips: { a: [-0.03592, 0.01620, 0.04386] as const, b: [-0.03084, 0.02507, -0.02552] as const, radius: 0.01278 },
      thumbBase: { a: [0.04806, -0.05581, 0.02726] as const, b: [0.03824, 0.00598, 0.08659] as const, radius: 0.01531 },
      thumbTip: { a: [0.03824, 0.00598, 0.08659] as const, b: [0.03906, 0.03432, 0.10825] as const, radius: 0.00977 },
    },
  },
  pinch: {
    propRadius: 0.00450,
    knuckleSpanM: 0.08500,
    segments: {
      forearm: { a: [-0.03465, -0.01507, -0.19339] as const, b: [-0.10613, 0.00632, -0.43199] as const, radius: 0.03963 },
      wrist: { a: [-0.03465, -0.01507, -0.19339] as const, b: [-0.02992, -0.02335, -0.14776] as const, radius: 0.03124 },
      palm: { a: [-0.02992, -0.02335, -0.14776] as const, b: [-0.01722, -0.02698, -0.07032] as const, radius: 0.03392 },
      index: { a: [-0.01604, 0.01624, -0.06184] as const, b: [-0.00446, 0.01450, 0.03408] as const, radius: 0.01128 },
      middle: { a: [-0.01756, -0.01666, -0.06301] as const, b: [0.00446, -0.01450, 0.04402] as const, radius: 0.01220 },
      ringPinky: { a: [-0.01763, -0.05376, -0.07821] as const, b: [-0.07090, -0.04045, -0.10565] as const, radius: 0.02569 },
      thumbBase: { a: [-0.02722, 0.01481, -0.14287] as const, b: [-0.06059, 0.05846, -0.07515] as const, radius: 0.01516 },
      thumbTip: { a: [-0.06059, 0.05846, -0.07515] as const, b: [-0.07456, 0.07563, -0.04717] as const, radius: 0.00979 },
    },
  },
};
