// scripts/gait-from-clip.ts
//
// npm run gait:curves -- <clip.glb> <name> [legLengthMetres]
// Writes src/lab/sdf-zombie/gait-curves/<name>.ts and prints the speed the
// stride implies for a body of the given leg length (default 0.84, the
// soldier: thigh 0.42 + shin 0.42), so motion-profile.ts's cruise/runBand
// can be set from measured numbers rather than guessed.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { parseGlb, curvesFromClip } from '../src/lab/sdf-zombie/glb-clip';

const [glb, name, legArg] = process.argv.slice(2);
if (!glb || !name) { console.error('usage: gait-from-clip <clip.glb> <name> [legLengthMetres]'); process.exit(2); }
const legLen = Number(legArg ?? 0.84);
const c = curvesFromClip(parseGlb(new Uint8Array(readFileSync(glb))), { name });
const fmt = (a: number[]) => '[' + a.map(v => v.toFixed(4)).join(', ') + ']';
const fmtB = (a: boolean[]) => '[' + a.map(v => (v ? 'true' : 'false')).join(', ') + ']';
const ident = name.replace(/-/g, '_').toUpperCase().replace(/[^A-Z0-9]/g, '_');
const src = `// GENERATED by scripts/gait-from-clip.ts from ${glb} — do not edit.
// ${c.n} samples over one cycle, phase 0 = left heel strike, angles in
// radians, lengths / leg length. Regenerate: npm run gait:curves -- ${glb} ${name}
import type { GaitCurves } from '../gait-curves';

export const ${ident}: GaitCurves = {
  name: '${name}',
  n: ${c.n},
  freq: ${c.freq.toFixed(5)},
  travel: ${c.travel.toFixed(5)},
  hipsY: ${fmt(c.hipsY)},
  L: { thigh: ${fmt(c.L.thigh)}, knee: ${fmt(c.L.knee)}, stance: ${fmtB(c.L.stance)} },
  R: { thigh: ${fmt(c.R.thigh)}, knee: ${fmt(c.R.knee)}, stance: ${fmtB(c.R.stance)} },
};
`;
mkdirSync('src/lab/sdf-zombie/gait-curves', { recursive: true });
const out = `src/lab/sdf-zombie/gait-curves/${name}.ts`;
writeFileSync(out, src);
const duty = c.L.stance.filter(Boolean).length / c.n;
const speed = (c.travel * legLen * c.freq) / duty;
console.log(`wrote ${out}: freq ${c.freq.toFixed(3)} Hz, duty ${duty.toFixed(2)}, travel ${(c.travel * legLen).toFixed(3)} m, ` +
  `peak knee ${Math.max(...c.L.knee).toFixed(2)} rad → implied speed ${speed.toFixed(2)} m/s for a ${legLen} m leg`);
