#!/usr/bin/env bash
set -euo pipefail
cd /Users/donny/Projects/blud/.claude/worktrees/codebase-refactor-reorganize-b3bd67
OUT="$HOME/.claude/dispatch/plans"
SLICES="render lighting probes gibs dynamite weapon player goo crowd bake vfx demo telemetry panels world boot"

for S in $SLICES; do
  # Capitalised forms for identifiers.
  CAP="$(echo "$S" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')"
  UPPER="$(echo "$S" | tr '[:lower:]' '[:upper:]')"
  TABLE="$(npx tsx scripts/slice-extract.ts "$S" 2>/dev/null | grep -E "^ *[0-9]+  ")"
  N="$(echo "$TABLE" | grep -c . || echo 0)"

  cat > "$OUT/2026-09-17-gamemain-slice-$S.md" <<EOF
---
title: "game-main decomposition - $S slice ($N bindings)"
status: pending
project: /Users/donny/Projects/blud
model: deepseek-flash
harness: dsh
branch: dispatch/gamemain-slice-$S
priority: 2
max_runtime: 45m
created: 2026-09-17
allowed_tools: Edit,Write,Bash,Read,Glob,Grep
setup: test "\$PWD" != /Users/donny/Projects/blud && ln -s /Users/donny/Projects/blud/node_modules node_modules
setup_timeout: 1m
---

## Context

Task from the \`game-main.ts\` decomposition plan.

**Goal:** \`src/lab/sdf-zombie/webgpu/game-main.ts\` is 14,763 lines with a ~9,400-line \`main()\` holding 498 bindings and 106 nested functions in ONE closure. We are lifting that state into a feature-sliced \`GameContext\`. **Your job is exactly one slice: \`$S\`.**

**You create exactly TWO new files. You do NOT edit \`game-main.ts\`.** A later codemod does that. If you edit \`game-main.ts\`, the task has failed.

**Exemplar — read this first, it is the shape you are copying:**
\`src/lab/sdf-zombie/webgpu/game-weapon-slots.ts\` and \`game-weapon-slots.test.ts\`.

## Your bindings

These $N bindings are the complete, authoritative field list for the \`$S\` slice. They were generated by AST analysis — do not add to or remove from this list. Format: \`line  slice  mut|once  name = initializer\`.

\`\`\`
$TABLE
\`\`\`

\`mut\` = reassigned somewhere in \`main()\`. \`once\` = assigned only at its declaration (still a slice field, because extracted functions must reach it).

## Instructions

- [ ] **Step 1: Read the exemplar and your bindings in context**

\`\`\`bash
sed -n '56,140p' src/lab/sdf-zombie/webgpu/game-weapon-slots.ts
\`\`\`

For each binding above, open \`src/lab/sdf-zombie/webgpu/game-main.ts\` at its line number to see the real declaration and infer its TypeScript type. Import types from their existing modules rather than redeclaring them; use \`unknown\` ONLY when no exported type exists.

- [ ] **Step 2: Write \`src/lab/sdf-zombie/webgpu/game-state-$S.ts\`**

Three exports, named exactly:

\`\`\`ts
export interface ${CAP}State { /* one field per binding above */ }
export function make${CAP}State(): ${CAP}State { /* initial values */ }
export const ${UPPER}_BINDINGS = { /* oldName: '$S.fieldName' */ } as const;
\`\`\`

Rules:
- **Field naming:** strip the redundant slice prefix. \`probeGatherRate\` -> \`gatherRate\`. \`gibAtlas\` -> \`atlas\`. If stripping leaves something meaningless or colliding, keep the fuller name.
- **Factory defaults:** if the initializer is a **literal** (\`0\`, \`true\`, \`'march'\`, \`null\`, \`[]\`), use that literal. If it is **computed** (a function call, a URL-param read, a \`new X()\`, anything referencing another variable), use a type-correct placeholder — \`0\`, \`false\`, \`null\`, \`[]\`. The real value is supplied later by an assignment at the original line, so a placeholder is correct and expected.
- **Every factory call must return a fresh object.** Never share an array or object between calls.
- \`${UPPER}_BINDINGS\` must contain **every** binding in the list above, mapping the old name to \`'$S.<fieldName>'\`.
- Plain mutable fields only. **No getters, setters, \`readonly\`, \`Object.freeze\` or proxies** — they change evaluation timing and break the pixel gate.

- [ ] **Step 3: Write \`src/lab/sdf-zombie/webgpu/game-state-$S.test.ts\`**

\`\`\`ts
import { describe, expect, it } from 'vitest';
import { ${UPPER}_BINDINGS, make${CAP}State } from './game-state-$S';

describe('make${CAP}State', () => {
  it('gives each call its own object', () => {
    expect(make${CAP}State()).not.toBe(make${CAP}State());
  });

  it('starts at the declared defaults', () => {
    const s = make${CAP}State();
    // Assert at least three fields whose game-main.ts initializer is a literal.
  });
});

describe('${UPPER}_BINDINGS', () => {
  it('maps every old name onto a field that exists on the state', () => {
    const s = make${CAP}State() as Record<string, unknown>;
    for (const [oldName, path] of Object.entries(${UPPER}_BINDINGS)) {
      expect(path.startsWith('$S.'), \\\`\\\${oldName} must map into the $S slice\\\`).toBe(true);
      expect(s).toHaveProperty(path.slice('$S.'.length));
    }
  });

  it('covers every binding assigned to this slice', () => {
    expect(Object.keys(${UPPER}_BINDINGS)).toHaveLength($N);
  });
});
\`\`\`

Fill in the three literal-default assertions from your actual bindings.

- [ ] **Step 4: Gate**

\`\`\`bash
npx tsc --noEmit -p .
npx vitest run src/lab/sdf-zombie/webgpu/game-state-$S.test.ts
\`\`\`

\`tsc\` will report errors about \`game-context.ts\` importing OTHER \`game-state-*\` modules that do not exist yet — **that is expected and not your problem**. There must be **no error in your two files**.

- [ ] **Step 5: Commit**

\`\`\`bash
git add src/lab/sdf-zombie/webgpu/game-state-$S.ts src/lab/sdf-zombie/webgpu/game-state-$S.test.ts
git commit -m "feat(state): $S slice — interface, factory and binding map"
\`\`\`

## Acceptance Criteria

- Exactly two new files created; \`game-main.ts\` untouched (\`git diff --name-only\` shows only your two files).
- \`${UPPER}_BINDINGS\` has exactly $N entries, matching the list above.
- \`npx vitest run src/lab/sdf-zombie/webgpu/game-state-$S.test.ts\` passes.
- No getters, setters, \`readonly\` or \`Object.freeze\` on state fields.
- Committed to the task branch. Do not merge, do not push to main.
EOF
  echo "wrote $S ($N bindings)"
done
