// scripts/zombie-skeleton-gen.ts — emits the RIBCAGE / SPINE / CLAVICLE /
// PELVIS lines of zombie.blob's `bones` block from an anatomical
// parametrisation, and checks every emitted prim against the flesh with the
// SAME sampler buildBody uses (boneBreach, 4 mm margin).
//
//   npx tsx scripts/zombie-skeleton-gen.ts            # print the block
//   npx tsx scripts/zombie-skeleton-gen.ts --check    # also splice it into
//                                                     # zombie.blob in memory
//                                                     # and run the real build
//   npx tsx scripts/zombie-skeleton-gen.ts --check --write   # ...and save it
//
// WHY A GENERATOR. A rib hoop is two quadratic Bezier capsules meeting at the
// flank, each written as `offset=` (start, relative to the rig spine point)
// + `tip=` (end, relative to the start) + `bend=` (control-point displacement
// from the chord midpoint). Twelve pairs is ~150 coordinates, every one of
// which is a function of five things an author actually reasons about: the
// rib's height on the spine, its half-width, its half-depth, how far it
// descends toward the sternum, and where the spine is at that height. Hand-
// typing the derived numbers is how the previous cage ended up 12 cm wide
// inside a 34 cm torso. The `.blob` stays the artefact (paste the output in,
// keep the prose comments); this file is the reasoning behind its numbers.
//
// Frame: world metres, rest pose. +x is the body's left, +y up, +z forward.
// Rig facts this leans on (resolved zombie.blob): spine bone (0,1.060,0) ->
// (0,1.398,0.041); pelvis bone (0,0.920,0) -> (0,1.060,0); hip joints at
// (+-0.100, 1.060, 0); shoulder joints at (+-0.200, 1.398, 0.041).
import { readFileSync, writeFileSync } from 'node:fs';
import { parseBlob } from '../src/lab/sdf-zombie/blob-parse';
import { compileBlob } from '../src/lab/sdf-zombie/blob-compile';
import { buildBody } from '../src/lab/sdf-zombie/build-body';
import { boneBreach, sdBody, BONE_CONTAINMENT_MARGIN } from '../src/lab/sdf-zombie/validate';
import type { Primitive, Vec3 } from '../src/lab/sdf-zombie/types';

type V = [number, number, number];
/** The line in zombie.blob below which everything up to GUT COIL is ours. */
const GEN_MARKER = '  # ---- generated by scripts/zombie-skeleton-gen.ts; edit the table there, not these lines ----';
const BLOB = new URL('../src/lab/sdf-zombie/characters/zombie.blob', import.meta.url).pathname;
const src = readFileSync(BLOB, 'utf8');
const body = buildBody(compileBlob(parseBlob(src)));
// Torso-only flesh: the arm flesh merges with the chest from ~y 1.10 up, so
// the FULL field would let a rib hide inside a shoulder. The gate is the full
// field (that is what validate checks); this one is the anatomical advisory.
const torsoOnly = { ...body, clusters: body.clusters.filter(c => c.limb === 'torso') };

const add = (a: V, b: V): V => [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
const sub = (a: V, b: V): V => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
const mul = (a: V, s: number): V => [a[0] * s, a[1] * s, a[2] * s];
const mid = (a: V, b: V): V => mul(add(a, b), 0.5);
const f = (v: number) => (Math.abs(v) < 5e-5 ? '0' : v.toFixed(4).replace(/0+$/, '').replace(/\.$/, ''));
const vec = (v: V) => `(${f(v[0])},${f(v[1])},${f(v[2])})`;
/** Control-point displacement that makes the quadratic pass through M at t=0.5. */
const bendThrough = (a: V, b: V, M: V): V => mul(sub(M, mid(a, b)), 2);
const bez = (a: V, c: V, b: V, t: number): V =>
  add(add(mul(a, (1 - t) * (1 - t)), mul(c, 2 * (1 - t) * t)), mul(b, t * t));

// Rig anchors.
const SPINE_H: V = [0, 1.06, 0], SPINE_T: V = [0, 1.398, 0.041];
const PELVIS_H: V = [0, 0.92, 0], PELVIS_T: V = [0, 1.06, 0];
const spineRig = (t: number): V => add(SPINE_H, mul(sub(SPINE_T, SPINE_H), t));
const pelvisRig = (s: number): V => add(PELVIS_H, mul(sub(PELVIS_T, PELVIS_H), s));

// ---------------------------------------------------------------------------
// THORACIC SPINE: one quadratic from the lumbar top to C7, bowed BACK
// (kyphosis) so the column sits where a back is — the rig axis runs up the
// middle of the flesh, and a spine there reads as a pillar, not a back.
// Back skin at mid-chest is z -0.134; the apex at -0.080 leaves ~3.5 cm of cover
// over an r 0.018 body. C7 comes forward to (0,1.40,0.028) to meet the derived
// neck bone, which starts at the neck bar's from=0.05 (0,1.406,0.044).
const TH_A: V = [0, 1.09, -0.06];
const TH_B: V = [0, 1.40, 0.028];
const TH_M: V = [0, 1.245, -0.072];
const TH_C = add(mid(TH_A, TH_B), bendThrough(TH_A, TH_B, TH_M));
/** y is linear in t on this curve (the control y is the chord-mid y). */
const spineAt = (y: number): V => bez(TH_A, TH_C, TH_B, (y - TH_A[1]) / (TH_B[1] - TH_A[1]));

// ---------------------------------------------------------------------------
// RIBS. Each row: head height on the spine, cage half-width A (x), cage
// half-depth B (z), descent from head to sternal end, tube radius, and where
// the front half ends (x of the sternal/costal end; null = floating, no front
// half). SIX pairs, not twelve (owner, 2026-09-03: "doesn't need the exact
// anatomical number — too many, maybe half, thicker individually"): heads run
// 1.375 -> 1.165 at 4.2 cm pitch, band r 0.0095-0.011 x tall 1.3 (~28 mm tall,
// ~21 mm thick), ~14 mm intercostal gap at the spine. The taper is the
// anatomy, compressed onto six: the thoracic inlet is narrow (~13 cm
// across in a person), rib 4 is the widest, ribs 5-6 stop on the costal
// margin short of the sternum.
interface Rib { y: number; A: number; B: number; drop: number; r: number; frontX: number | null; floatTheta?: number }
// 2026-09-22: ribs 4-6 narrowed (A 0.160/0.145/0.120 -> 0.150/0.133/0.110),
// the kyphosis apex brought forward (z -0.080 -> -0.072), BACK_FLAT 0.78 ->
// 0.72 and the iliac APEX x 0.128 -> 0.124: half-strength blends (3662c1ca)
// thinned the waist seam and 11 of these bones broke the 4 mm margin there.
const RIBS: Rib[] = [
  { y: 1.375, A: 0.075, B: 0.050, drop: 0.020, r: 0.0095, frontX: 0.024 },
  { y: 1.333, A: 0.125, B: 0.082, drop: 0.036, r: 0.0105, frontX: 0.024 },
  { y: 1.291, A: 0.155, B: 0.092, drop: 0.050, r: 0.0110, frontX: 0.024 },
  { y: 1.249, A: 0.150, B: 0.090, drop: 0.058, r: 0.0110, frontX: 0.024 },
  { y: 1.207, A: 0.133, B: 0.077, drop: 0.060, r: 0.0105, frontX: 0.050 },
  { y: 1.165, A: 0.110, B: 0.074, drop: 0.052, r: 0.0095, frontX: 0.080 },
];
/** x of the rib head: on the flank of an r 0.018 vertebral body. */
const HEAD_X = 0.017;
/** The rib angle sits BEHIND the vertebral body, so the cage's back wall is
 *  this far behind the spine's centreline. 0.025 is nearer the anatomy, but
 *  the zombie's back is a blended ellipsoid, rounder than a person's, and at
 *  0.025 the back-flank corner of ribs 6-10 broke the 4 mm margin (first
 *  generator run, 2026-09-03). */
const ANGLE_BACK = 0.012;
/** How far the BACK half's mid-curve point sits behind the cage centre, as a
 *  fraction of the elliptical 45-degree point. 1 is a true ellipse; the
 *  zombie's back-flank is much rounder than its cross-section at x 0 suggests
 *  (probed 2026-09-03: at y 1.19 the half-width is 0.181 at z 0 but 0.139 at
 *  z -0.07 and 0.114 at z -0.09), so a true elliptical corner breaks the
 *  margin on the fat six-rib cage. 0.78 keeps the cage's back a flatter arc,
 *  which is also nearer the kidney section of a real thorax. */
const BACK_FLAT = 0.72;

interface Emitted { line: string; prim: Primitive; label: string }
const out: Emitted[] = [];

/** A bar on `bone` written as from=t to=t offset= tip= bend=. `both` mirrors. */
function bar(bone: 'spine' | 'pelvis', t: number, a: V, b: V, M: V | null, r: number,
  extra: string, both: boolean, label: string, comment?: string) {
  const rig = bone === 'spine' ? spineRig(t) : pelvisRig(t);
  const offset = sub(a, rig), tip = sub(b, a);
  const bend = M ? bendThrough(a, b, M) : null;
  const words = [`bar torso on ${bone}`, `from=${f(t)} to=${f(t)}`, `offset=${vec(offset)}`, `tip=${vec(tip)}`];
  if (bend) words.push(`bend=${vec(bend)}`);
  words.push(`r=${f(r)}`);
  if (extra) words.push(extra);
  if (both) words.push('both');
  const line = (comment ? `  # ${comment}\n` : '') + '  ' + words.join(' ');
  const r2m = /r2=([\d.]+)/.exec(extra);
  const sc = (k: string) => { const m = new RegExp(`${k}=([\\d.]+)`).exec(extra); return m ? Number(m[1]) : 1; };
  const prim = {
    a, b, radius: r, ...(r2m ? { radiusB: Number(r2m[1]) } : {}),
    scale: [sc('wide'), sc('tall'), sc('deep')] as Vec3,
    ...(bend ? { bend: bend as Vec3 } : {}), op: 'bone', limb: 'torso', blendK: 0, cluster: 0, bone,
  } as unknown as Primitive;
  out.push({ line, prim, label });
  if (both) {
    const flip = (v: V): V => [-v[0], v[1], v[2]];
    const pm = { ...prim, a: flip(a), b: flip(b), ...(bend ? { bend: flip(bend) as Vec3 } : {}) } as Primitive;
    out.push({ line: '', prim: pm, label: label + ' (r)' });
  }
}

// Spine: split the thoracic quadratic at t=0.5 (de Casteljau) so the lower
// half binds with the lower ribs (hips joint) and the upper half with the
// upper ribs (chest joint) — same curve, two prims, no shear at the join.
{
  const c1 = mid(TH_A, TH_C), c2 = mid(TH_C, TH_B);
  const lo = { a: TH_A, b: TH_M, M: bez(TH_A, c1, TH_M, 0.5) };
  const hi = { a: TH_M, b: TH_B, M: bez(TH_M, c2, TH_B, 0.5) };
  bar('spine', 0.1, lo.a, lo.b, lo.M, 0.018, 'deep=0.85', false, 'thoracic lower',
    `Thoracic column, lower half (T12 -> apex of the kyphosis at y ${f(TH_M[1])}, z ${f(TH_M[2])}).`);
  bar('spine', 0.9, hi.a, hi.b, hi.M, 0.018, 'deep=0.85', false, 'thoracic upper',
    'Thoracic column, upper half (apex -> C7 at (0,1.40,0.028), meeting the derived neck bone).');
  // Lumbar: L5 -> L1 with a touch of lordosis (forward), on the pelvis bone so
  // it rides with the hips joint like the sacrum below it.
  const LA: V = [0, 1.0, -0.047], LB: V = TH_A;
  bar('pelvis', 0.6, LA, LB, add(mid(LA, LB), [0, 0, 0.01]), 0.018, 'deep=0.85', false, 'lumbar',
    'Lumbar column: sacral promontory (0,1.00,-0.047) up to T12, bowed 1 cm forward (lordosis).');
}

// Ribs.
RIBS.forEach((rib, i) => {
  const k = i + 1;
  const sp = spineAt(rib.y);
  const zc = sp[2] - ANGLE_BACK + rib.B;               // cage centre z at this rib
  const head: V = [HEAD_X, rib.y, sp[2]];
  const th0 = Math.asin(HEAD_X / rib.A);
  const thEnd = rib.frontX === null ? rib.floatTheta! : Math.PI - Math.asin(rib.frontX / rib.A);
  const onCage = (th: number): V => [
    rib.A * Math.sin(th),
    rib.y - rib.drop * (th - th0) / (thEnd - th0),
    // Behind the centre (cos > 0) the arc is flattened by BACK_FLAT; the
    // head itself (th0, on the spine) and everything forward stay elliptical.
    zc - rib.B * Math.cos(th) * (th > th0 + 1e-9 && th < Math.PI / 2 ? BACK_FLAT : 1),
  ];
  const t = (rib.y - SPINE_H[1]) / (SPINE_T[1] - SPINE_H[1]);
  const tall = 'tall=1.3';
  if (rib.frontX === null) {
    // Floating rib: one arc from the head out and down, ending free.
    const tip = onCage(thEnd);
    bar('spine', t, head, tip, onCage((th0 + thEnd) / 2), rib.r, tall, true, `rib ${k} (floating)`,
      `Rib ${k}, floating: head y ${f(rib.y)}, out to x ${f(tip[0])}, ${f(rib.drop)} down, no sternal end.`);
    return;
  }
  const flank = onCage(Math.PI / 2);
  const front = onCage(thEnd);
  bar('spine', t, head, flank, onCage((th0 + Math.PI / 2) / 2), rib.r, tall, true, `rib ${k} back`,
    `Rib ${k}: head y ${f(rib.y)}, cage half-width ${f(rib.A)} / half-depth ${f(rib.B)}, descends ${f(rib.drop)} to the ` +
    (rib.frontX > 0.03 ? 'costal margin' : 'sternum') + '. Back half: vertebra -> rib angle -> flank.');
  bar('spine', t, flank, front, onCage((Math.PI / 2 + thEnd) / 2), rib.r, `r2=${f(rib.r * 0.82)} ${tall}`, true, `rib ${k} front`,
    undefined);
});

// Sternum: through the sternal ends of the true ribs (1-7). Flat: 48 mm wide,
// 12 mm thick, like the bone.
{
  const sternalPts = RIBS.filter(r => r.frontX !== null && r.frontX <= 0.03).map(rib => {
    const sp = spineAt(rib.y);
    const zc = sp[2] - ANGLE_BACK + rib.B;
    return { y: rib.y - rib.drop, z: zc + rib.B * Math.cos(Math.asin(rib.frontX! / rib.A)) };
  });
  const zFront = (y: number): number => {
    const pts = sternalPts.slice().sort((p, q) => q.y - p.y);
    if (y >= pts[0]!.y) return pts[0]!.z;
    for (let i = 0; i + 1 < pts.length; i++) {
      const p = pts[i]!, q = pts[i + 1]!;
      if (y <= p.y && y >= q.y) return p.z + (q.z - p.z) * (p.y - y) / (p.y - q.y);
    }
    return pts[pts.length - 1]!.z;
  };
  const yTop = 1.372, yBot = sternalPts[sternalPts.length - 1]!.y - 0.01;
  const a: V = [0, yTop, zFront(yTop)], b: V = [0, yBot, zFront(yBot)];
  const ym = (yTop + yBot) / 2;
  bar('spine', 0.75, a, b, [0, ym, zFront(ym)], 0.010, 'wide=2.4 deep=0.6', false, 'sternum',
    `Sternum: manubrium at y ${f(yTop)} down to the xiphoid at y ${f(yBot)}, riding the ribs' sternal ends in z.`);

  // Clavicles: sternal end on the manubrium, acromial end just medial of the
  // shoulder joint (0.2,1.398,0.041), inside the shoulder ball (r 0.072 at
  // x 0.18). Bowed a touch forward and up through the middle. Written `both`
  // on the spine (not `mirror` on the clavicle bone) so it is a TORSO bone,
  // rigid with the chest joint, and a chest wound can expose it.
  const ca: V = [0.026, yTop, zFront(yTop)], cb: V = [0.185, 1.402, 0.035];
  bar('spine', 1.0, ca, cb, [0.105, 1.392, 0.052], 0.0075, '', true, 'clavicle',
    'Clavicle: manubrium -> acromion, bowed forward through (0.105,1.392,0.052).');
}

// PELVIS as a SOLID MASS (owner, 2026-09-03: "needs to be a big solid mass,
// not doodly lines"). The first cut was a fan of 13 mm bars per side; at
// tube scale that reads as wire. Now: a fat sacrum wedge, per side one thick
// iliac blade (a bar from the acetabular hub up and out to the crest, wide
// enough to be a plate, capped by a thick crest arc), and a fat pubic ring.
// Every radius here is 2-3x the rib radius on purpose.
{
  const SA: V = [0, 1.005, -0.047], SB: V = [0, 0.925, -0.036];
  bar('pelvis', 0.5, SA, SB, [0, 0.965, -0.070], 0.032, 'r2=0.016 wide=1.5 deep=0.7', false, 'sacrum',
    'Sacrum: promontory (0,1.005,-0.047) curving back to z -0.070 then forward to the coccyx. Fat wedge, 48 mm across at the top.');
  const HUB: V = [0.078, 1.045, -0.006];
  const PSIS: V = [0.040, 1.055, -0.070];
  const APEX: V = [0.124, 1.100, -0.014];
  const ASIS: V = [0.118, 1.070, 0.050];
  // The blade: hub -> crest apex, thick, flattened front-to-back so it reads
  // as a plate seen edge-on from the side and a wing from the front.
  bar('pelvis', 0.5, HUB, APEX, null, 0.030, 'deep=0.6 tall=1.1', true, 'iliac blade',
    'Iliac blade: acetabular hub (0.078,1.045,-0.006) up and out to the crest apex (0.128,1.100,-0.014); r 0.030, flattened front-to-back.');
  bar('pelvis', 0.5, PSIS, ASIS, APEX, 0.018, 'deep=0.8', true, 'iliac crest',
    'Iliac crest: PSIS -> apex -> ASIS, the thick rim over the blade.');
  bar('pelvis', 0.5, HUB, PSIS, null, 0.022, '', true, 'ilium to sacrum',
    'Ilium back to the sacro-iliac joint.');
  const SYM: V = [0.014, 0.935, 0.056];
  const TUB: V = [0.056, 0.905, -0.026];
  bar('pelvis', 0.5, HUB, SYM, null, 0.018, '', true, 'superior pubic ramus', 'Pubic ring: superior ramus hub -> symphysis (0.014,0.935,0.056),');
  bar('pelvis', 0.5, HUB, TUB, null, 0.022, '', true, 'ischium', 'ischium hub -> sit bone (0.056,0.905,-0.026), the fat lower mass,');
  bar('pelvis', 0.5, TUB, SYM, null, 0.015, '', true, 'ischiopubic ramus', 'ischiopubic ramus closing the ring underneath.');
}

// ---------------------------------------------------------------------------
// Report + emit.
const axial: V[] = [PELVIS_H, PELVIS_T, SPINE_T, [0, 1.549, 0.093]];
const all: V[] = [...axial, [0.1, 1.06, 0], [-0.1, 1.06, 0], [0.2, 1.398, 0.041], [-0.2, 1.398, 0.041]];
const nearest = (p: V, js: V[]) => js.reduce((bi, j, i) => Math.hypot(...sub(p, j)) < Math.hypot(...sub(p, js[bi]!)) ? i : bi, 0);
const dist = (p: V, b: typeof body) => sdBody(p as Vec3, b);
let worst = 0; let bad = 0; let armHidden = 0;
const lines: string[] = [];
for (const e of out) {
  // Stricter than the real gate by SLACK: the emitted numbers are rounded to
  // 4 decimals and the compiled prim lands ~0.2 mm off this one — rib 5's
  // back half once passed here at 4.0 mm and failed the build at 3.93 mm.
  const SLACK = 0.0012;
  const probe = { ...e.prim, radius: e.prim.radius + SLACK, ...(e.prim.radiusB === undefined ? {} : { radiusB: e.prim.radiusB + SLACK }) } as Primitive;
  const breachFull = boneBreach(body, probe);
  const breachTorso = boneBreach(torsoOnly, probe);
  // Clearance number for the report: the deepest the flesh gets at the
  // shallowest sampled tube point, via the same sampler's failure point.
  const m = mid(e.prim.a as V, e.prim.b as V);
  const jAll = nearest(m, all), jAx = nearest(m, axial);
  const note = [
    breachFull ? `BREACH full at ${vec(breachFull as V)} (sd ${(dist(breachFull as V, body) * 1000).toFixed(1)} mm)` : 'ok',
    breachTorso ? `arm-hidden at ${vec(breachTorso as V)}` : '',
    jAll >= 4 ? `mid nearest ANY joint = ${jAll >= 6 ? 'shoulder' : 'hip'} (axial pick: ${['pelvis', 'hips', 'chest', 'neck'][jAx]})` : '',
  ].filter(Boolean).join('; ');
  if (breachFull) bad++;
  if (!breachFull && breachTorso) armHidden++;
  worst = Math.max(worst, 0);
  if (process.argv.includes('--verbose') || breachFull || breachTorso)
    console.error(`${e.label.padEnd(26)} ${note}`);
  if (process.env.GEN_DEBUG && e.label.startsWith(process.env.GEN_DEBUG))
    console.error('DEBUG', e.label, JSON.stringify({ a: e.prim.a, b: e.prim.b, r: e.prim.radius, r2: e.prim.radiusB, scale: e.prim.scale, bend: e.prim.bend }));
  if (e.line) lines.push(e.line);
}
console.error(`emitted ${lines.length} lines / ${out.length} prims; breaches (full flesh): ${bad}; inside arm flesh only: ${armHidden}; margin ${BONE_CONTAINMENT_MARGIN} m`);
console.log(lines.join('\n'));

if (process.argv.includes('--check')) {
  // Splice: replace everything between the generated-block marker and the
  // GUT COIL comment in the current file with the generated lines, then build.
  const start = src.indexOf(GEN_MARKER);
  const end = src.indexOf('  # GUT COIL');
  if (start < 0 || end < 0) throw new Error('could not find the generated-block marker / GUT COIL in zombie.blob');
  const spliced = src.slice(0, start + GEN_MARKER.length) + '\n' + lines.join('\n') + '\n\n' + src.slice(end);
  const built = buildBody(compileBlob(parseBlob(spliced)));
  console.error(`--check: flesh ${built.prims.length} + bone ${built.bonePrims.length} = ${built.prims.length + built.bonePrims.length}; errors: ${built.errors.length}`);
  for (const err of built.errors) console.error('  ' + err);
  if (process.argv.includes('--write') && built.errors.length === 0) {
    writeFileSync(BLOB, spliced);
    console.error(`--write: zombie.blob updated`);
  }
}
